#ifndef __APPCONTROL_DEF_H__
#define __APPCONTROL_DEF_H__

// Load_Process
#define PROCESS_COM_USE_FLAG				0
#define PROCESS_COM_CALI_METER				1
#define PROCESS_COM_DISPLAY					2
#define PROCESS_COM_ANALOG_METER			3

#define MAX_PROCESS_GROUP					6
#define PROCESS_GROUP_COA					0
#define PROCESS_GROUP_COB					1
#define PROCESS_GROUP_COC					2
#define PROCESS_GROUP_COD					3
#define PROCESS_GROUP_JIG					4
#define PROCESS_GROUP_ETC					5

#define PROCESS_DATA_SAVE					0
#define PROCESS_CALI_SERVER					1
#define PROCESS_TIME_SCHEDULE				2	//kjhw_160418
#define PROCESS_TEMP1_CLIENT				3	//KHK_190902
#define PROCESS_TEMP2_CLIENT				4
#define PROCESS_TEMP3_CLIENT				5
#define PROCESS_TEMP4_CLIENT				6
#define PROCESS_MODULE_CONTROL				7

// AppControl Signal
#define APP_SIG_APP_CONTROL_PROCESS			0
#define APP_SIG_DATA_SAVE_PROCESS			1
#define APP_SIG_CALI_METER_PROCESS			2
#define APP_SIG_CALI_CONTROL_PROCESS		3
#define APP_SIG_ANALOG_METER_PROCESS		4
#define APP_SIG_MODULE_CONTROL_PROCESS		5
#define APP_SIG_TEMP_CONTROLLER_PROCESS		6
#define APP_SIG_BCR_PROCESS					7
#define APP_SIG_CALI_SERVER_PROCESS			8
#define APP_SIG_TIME_SCHEDULE_PROCESS		9 //kjh_160418

#define APP_SIG_COA1_CLIENT_PROCESS			10
#define APP_SIG_COA2_CLIENT_PROCESS			11
#define APP_SIG_COA3_CLIENT_PROCESS			12
#define APP_SIG_COA4_CLIENT_PROCESS			13
#define APP_SIG_COB1_CLIENT_PROCESS			14
#define APP_SIG_COB2_CLIENT_PROCESS			15
#define APP_SIG_COB3_CLIENT_PROCESS			16
#define APP_SIG_COB4_CLIENT_PROCESS			17
#define APP_SIG_COC1_CLIENT_PROCESS			18
#define APP_SIG_COC2_CLIENT_PROCESS			19
#define APP_SIG_COC3_CLIENT_PROCESS			20
#define APP_SIG_COC4_CLIENT_PROCESS			21
#define APP_SIG_COD1_CLIENT_PROCESS			22
#define APP_SIG_COD2_CLIENT_PROCESS			23
#define APP_SIG_COD3_CLIENT_PROCESS			24
#define APP_SIG_COD4_CLIENT_PROCESS			25

#define APP_SIG_JIG1_CONTROL_PROCESS		30
#define APP_SIG_JIG2_CONTROL_PROCESS		31
#define APP_SIG_JIG3_CONTROL_PROCESS		32
#define APP_SIG_JIG4_CONTROL_PROCESS		33
#define APP_SIG_JIG5_CONTROL_PROCESS		34
#define APP_SIG_JIG6_CONTROL_PROCESS		35
#define APP_SIG_JIG7_CONTROL_PROCESS		36
#define APP_SIG_JIG8_CONTROL_PROCESS		37

#define APP_SIG_APP_CONTROL_PROCESS_CHECK	50
#define APP_SIG_DATA_SAVE_PROCESS_CHECK		51
#define APP_SIG_CALI_METER_PROCESS_CHECK	52
#define APP_SIG_CALI_CONTROL_PROCESS_CHECK	53
#define APP_SIG_ANALOG_METER_PROCESS_CHECK	54
#define APP_SIG_MODULE_CONTROL_PROCESS_CHECK	55
#define APP_SIG_TEMP_CONTROLLER_PROCESS_CHECK	56
#define APP_SIG_BCR_PROCESS_CHECK			57
#define APP_SIG_CALI_SERVER_PROCESS_CHECK	58
#define APP_SIG_TIME_SCHEDULE_PROCESS_CHECK	59 //kjhw_160418

#define APP_SIG_COA1_CLIENT_PROCESS_CHECK	60
#define APP_SIG_COA2_CLIENT_PROCESS_CHECK	61
#define APP_SIG_COA3_CLIENT_PROCESS_CHECK	62
#define APP_SIG_COA4_CLIENT_PROCESS_CHECK	63
#define APP_SIG_COB1_CLIENT_PROCESS_CHECK	64
#define APP_SIG_COB2_CLIENT_PROCESS_CHECK	65
#define APP_SIG_COB3_CLIENT_PROCESS_CHECK	66
#define APP_SIG_COB4_CLIENT_PROCESS_CHECK	67
#define APP_SIG_COC1_CLIENT_PROCESS_CHECK	68
#define APP_SIG_COC2_CLIENT_PROCESS_CHECK	69
#define APP_SIG_COC3_CLIENT_PROCESS_CHECK	70
#define APP_SIG_COC4_CLIENT_PROCESS_CHECK	71
#define APP_SIG_COD1_CLIENT_PROCESS_CHECK	72
#define APP_SIG_COD2_CLIENT_PROCESS_CHECK	73
#define APP_SIG_COD3_CLIENT_PROCESS_CHECK	74
#define APP_SIG_COD4_CLIENT_PROCESS_CHECK	75

#define APP_SIG_JIG1_CONTROL_PROCESS_CHECK	76
#define APP_SIG_JIG2_CONTROL_PROCESS_CHECK	77
#define APP_SIG_JIG3_CONTROL_PROCESS_CHECK	78
#define APP_SIG_JIG4_CONTROL_PROCESS_CHECK	79

#define APP_SIG_TIMER_1SEC					80
#define APP_SIG_QUIT						81
#define APP_SIG_ANALOG_METER_START			82
#define APP_SIG_QUIT_TYPE					83
#define APP_SIG_REAL_TIME_REQUEST			84
#define APP_SIG_CALI_METER_START			85
#define APP_SIG_CALI_UPDATE					86
#define APP_SIG_QUIT_VALUE					87
#define APP_SIG_CALI_DA_UPDATE				88

//20190905 KHK-----------------------------
#define APP_SIG_TEMP1_CLIENT_PROCESS		89
#define APP_SIG_TEMP2_CLIENT_PROCESS		90
#define APP_SIG_TEMP3_CLIENT_PROCESS		91
#define APP_SIG_TEMP4_CLIENT_PROCESS		92
#define APP_SIG_TEMP1_CLIENT_PROCESS_CHECK	93
#define APP_SIG_TEMP2_CLIENT_PROCESS_CHECK	94
#define APP_SIG_TEMP3_CLIENT_PROCESS_CHECK	95
#define APP_SIG_TEMP4_CLIENT_PROCESS_CHECK	96
//-----------------------------------------
#define	APP_SIG_UPDATE_PROCESS				97	//ktg_231031
#define	APP_SIG_UPDATE_PROCESS_CHECK		98	//ktg_231031
#endif
