#ifndef __MESSAGE_DEF_H__
#define __MESSAGE_DEF_H__

//#define MAX_MSG_RING						80
#define MAX_MSG_RING						100	//jhkw_211028
#define MAX_SAVE_MSG_RING					2
#define MAX_RECORD_MSG_RING					2
#define MAX_PULSE_MSG_RING					2
#define MAX_F_SAVE_MSG_RING					12
#define MAX_F_DCIR_SAVE_MSG_RING			8
#define MAX_SAVE_CH							8
#define MAX_PULSE_CH						8

#define MAX_MSG								128
#define MAX_SAVE_MSG						1000
#define MAX_RECORD_MSG						100
#define MAX_PULSE_MSG						10000
#define MAX_F_SAVE_MSG						20
#define MAX_F_DCIR_SAVE_MSG					8

//message direction
#define APP_TO_MODULE						0
#define APP_TO_IO							1
#define APP_TO_JIGM							2
#define APP_TO_METER						3
#define APP_TO_METER2						4
#define APP_TO_COA1							5
#define APP_TO_COA2							6
#define APP_TO_COB1							7
#define APP_TO_COB2							8
#define APP_TO_COC1							9
#define APP_TO_COC2							10
#define APP_TO_COD1							11
#define APP_TO_COD2							12
#define DATASAVE_TO_MODULE					13
#define DATASAVE_TO_COA1					14
#define DATASAVE_TO_COA2					15
#define DATASAVE_TO_COB1					16
#define DATASAVE_TO_COB2					17
#define DATASAVE_TO_COC1					18
#define DATASAVE_TO_COC2					19

#define COA1_TO_MODULE						20
#define COA2_TO_MODULE						21
#define COA1_TO_APP							22
#define COA2_TO_APP							23
#define COB1_TO_MODULE						24
#define COB2_TO_MODULE						25
#define COB1_TO_APP							26
#define COB2_TO_APP							27
#define COC1_TO_MODULE						28
#define COC2_TO_MODULE						29
#define COC1_TO_APP							30
#define COC2_TO_APP							31
#define COD1_TO_MODULE						32
#define COD2_TO_MODULE						33
#define COD1_TO_APP							34
#define COD2_TO_APP							35

#define COA1_TO_METER						40
#define COA2_TO_METER						41
#define COB1_TO_METER						42
#define COB2_TO_METER						43
#define COC1_TO_METER						44
#define COC2_TO_METER						45

#define JIGC1_TO_IO							46
#define JIGC2_TO_IO							47
#define JIGC1_TO_JIGM						48
#define JIGC2_TO_JIGM						49

#define JIGC_TO_COB1						50
#define JIGC_TO_COB2						51

#define JIGM_TO_JIGC1						52
#define JIGM_TO_JIGC2						53
#define JIGM_TO_MODULE						54

#define IO_TO_MODULE						55
#define IO_TO_APP							85	//csk_200113

// TimeSchedule to Module
#define TIMESCH_TO_COA1						56 //kjh_160418

#define MODULE_TO_TIMESCH					59 //kjh_160418
#define MODULE_TO_APP						60
#define MODULE_TO_DATASAVE					61
#define MODULE_TO_COA1						62
#define MODULE_TO_COA2						63
#define MODULE_TO_COB1						64
#define MODULE_TO_COB2						65
#define MODULE_TO_COC1						66
#define MODULE_TO_COC2						67
#define MODULE_TO_JIGM						68
#define MODULE_TO_IO						69
#define MODULE_TO_METER						70

#define METER_TO_COA1						71
#define METER_TO_COA2						72
#define METER_TO_COB1						73
#define METER_TO_COB2						74
#define METER_TO_COC1						75
#define METER_TO_COC2						76
#define METER_TO_MODULE						77

// COB to Jig
#define COB1_TO_JIGC1						78
#define COB2_TO_JIGC2						79

//20190905 KHK------------------------------
#define APP_TO_TEMP1						80
#define APP_TO_TEMP2						81
#define APP_TO_TEMP3						82
#define APP_TO_TEMP4						83

#define MODULE_TO_TEMP1						84
#define MODULE_TO_TEMP2						85
#define MODULE_TO_TEMP3						86
#define MODULE_TO_TEMP4						87
//------------------------------------------
#define UPDATE_TO_IO						88	//ktg_231031
#define IO_TO_UPDATE						89	//ktg_231031

// 0 AppControl to Module
#define MSG_APP_MODULE_EXIT					1
#define MSG_APP_MODULE_CH_CALI				2
#define MSG_APP_MODULE_SAVE_START			3
#define MSG_APP_MODULE_SAVE_STOP			4
#define MSG_APP_MODULE_CAN_INITIALIZE		5
#define MSG_APP_MODULE_CAN_STATUS_REQUEST	6
#define MSG_APP_MODULE_CAN_BAUDRATE_SET		7
#define MSG_APP_MODULE_CAN_ERROR_CLEAR		8
#define MSG_APP_MODULE_RS232_BAUDRATE_SET	9
#define MSG_APP_MODULE_CAN_DATA_CLEAR		10
#define MSG_APP_MODULE_CAN_ABORT_TRANSMISSION	11
#define MSG_APP_MODULE_CAN_TEST1			12
#define MSG_APP_MODULE_CAN_TEST2			13
#define MSG_APP_MODULE_CAN_TEST3			14
#define MSG_APP_MODULE_READ_BCR				15
#define MSG_APP_MODULE_TEST_PAUSE			16
#define MSG_APP_MODULE_TEST_CONTINUE		17
#define MSG_APP_MODULE_TEST_STOP			18
#define MSG_APP_MODULE_TEST_BCR_READ		19
#define MSG_APP_MODULE_CH_CALI_UPDATE		20
#define MSG_APP_MODULE_CH_IO_SET			21
#define MSG_APP_MODULE_CALI_DAV				22 //kjg_110814_s
#define MSG_APP_MODULE_CALI_DAI				23
#define MSG_APP_MODULE_CALI_DAI_SW			24
#define MSG_APP_MODULE_CALI_RANGE			25
#define MSG_APP_MODULE_CALI_SWITCH_ON_OFF	26
#define MSG_APP_MODULE_CALI_V				27
#define MSG_APP_MODULE_CALI_I_CHARGE		28
#define MSG_APP_MODULE_CALI_I_DISCHARGE		29
#define MSG_APP_MODULE_CALI_RUN				30
#define MSG_APP_MODULE_CALI_STOP			31
#define MSG_APP_MODULE_CALI_CHARGE			32
#define MSG_APP_MODULE_CALI_DISCHARGE		33 //kjg_110814_e
#define MSG_APP_MODULE_CAN_FD_TEST			34 //kjg_180405

// 1 AppControl to ioControl
#define MSG_APP_IO_EXIT						1
#define MSG_APP_IO_SHUTDOWN					2

// 2 AppControl to JigManager
#define MSG_APP_JIGM_TRY_CONTACT			1
#define MSG_APP_JIGM_TRY_DISCONTACT			2

// 3 AppControl to Meter
#define MSG_APP_METER_INITIALIZE			1
#define MSG_APP_METER_REQUEST				2
#define MSG_APP_METER_TEST					3
#define MSG_APP_METER_DISPLAY_START			4

// 4 AppControl to TempController
#define MSG_APP_TEMPCON_INITIALIZE			1
#define MSG_APP_TEMPCON_CONNECT				2
#define MSG_APP_TEMPCON_REQUEST				3
#define MSG_APP_TEMPCON_MEASURE				4

// 6 AppControl to Meter2
#define MSG_APP_METER2_INITIALIZE			1
#define MSG_APP_METER2_REQUEST				2
#define MSG_APP_METER2_MEASURE				3

// 7 AppControl to COA?Client
#define MSG_APP_COA_REAL_TIME_REQUEST		1
#define MSG_APP_COA_WRITE_VBF_DATA_REPLY	2
#define MSG_APP_COA_TEST_COND_CONVERSION_END	3
#define MSG_APP_COA_READ_TH_TABLE_SET_REPLY		4 //kjhw_181111
#define MSG_APP_COA_READ_HUMIDITY_TABLE_SET_REPLY	5 //csk_200207
#define MSG_APP_COA_CMD_CALI_TEMP_REPLY		6			//khj_210802
#define MSG_APP_COA_READ_CAN_TH_TABLE_SET_REPLY	7 //ktg_220614

// 8 AppControl to COB?Client
#define MSG_APP_COB_REAL_TIME_REQUEST		1
#define MSG_APP_COB_TEST_FUNCTION			2
#define MSG_APP_COB_PLC_DOOR_OPEN			3
#define MSG_APP_COB_PLC_DOOR_CLOSE			4
#define MSG_APP_COB_PLC_FAULT_READ			5
#define MSG_APP_COB_JOB_CHANGE				6
#define MSG_APP_COB_TRY_CONTACT				7
#define MSG_APP_COB_TRY_DISCONTACT			8
#define MSG_APP_COB_PITCH_CHANGE			9

// 9 AppControl to COC?Client
#define MSG_APP_COC_REAL_TIME_REQUEST		1

// 11 AppControl to COD?Client
#define MSG_APP_COD_REAL_TIME_REQUEST		1

// 20 DataSave to Module
#define MSG_DATASAVE_MODULE_CMD_RUN			1
#define MSG_DATASAVE_MODULE_CMD_CONTINUE	2
#define MSG_DATASAVE_MODULE_FAIL			3
#define MSG_DATASAVE_MODULE_READ_PATTERN_FILE_END	4
#define MSG_DATASAVE_MODULE_READ_USERMAP_FILE_END	5 //kjhw_140828

#define MSG_DATASAVE_MODULE_CALI_NORMAL_RESULT_SAVED	12
#define MSG_DATASAVE_MODULE_CALI_CHECK_RESULT_SAVED	13

#define MSG_DATASAVE_MODULE_SAVED_FILE_DELETE_COMPLETE	20

// 21~ DataSave to COA?Client
#define MSG_DATASAVE_COA_CALI_NORMAL_RESULT_SEND	1
#define MSG_DATASAVE_COA_CALI_CHECK_RESULT_SEND	2

// 21~ DataSave to COB?Client
#define MSG_DATASAVE_COB_CALI_NORMAL_RESULT_SEND	1
#define MSG_DATASAVE_COB_CALI_CHECK_RESULT_SEND	2

// 21~ DataSave to COC?Client
#define MSG_DATASAVE_COC_CALI_NORMAL_RESULT_SEND	1
#define MSG_DATASAVE_COC_CALI_CHECK_RESULT_SEND	2

// 32~ JigControl to IOComm
#define MSG_JIG_MAIN_CYL					1
#define MSG_JIG_LATCH_CYL					2
#define MSG_JIG_GRIP_CYL					3
#define MSG_JIG_TOWER_LAMP_RED				4
#define MSG_JIG_TOWER_LAMP_AMBER			5
#define MSG_JIG_TOWER_LAMP_GREEN			6
#define MSG_JIG_FAN_1						7
#define MSG_JIG_FAN_2						8
#define MSG_JIG_TEMP_READ					9
#define MSG_JIG_IO_READ						10
#define MSG_JIG_START_LAMP					11
#define MSG_JIG_STOP_LAMP					12
#define MSG_JIG_CONTINUE_LAMP				13

// 40~ COA?Client to Module
#define MSG_COA_MODULE_CMD_RUN				1
#define MSG_COA_MODULE_CMD_STOP				2
#define MSG_COA_MODULE_CMD_PAUSE			3
#define MSG_COA_MODULE_CMD_CONTINUE			4
#define MSG_COA_MODULE_CMD_NEXT_STEP		5
#define MSG_COA_MODULE_CMD_RESET			6
#define MSG_COA_MODULE_CMD_CLEAR			7
#define MSG_COA_MODULE_WORK_MODE			8
#define MSG_COA_MODULE_SAVE_MSG_FLAG		9
#define MSG_COA_MODULE_CMD_CHECK			10
#define MSG_COA_MODULE_CH_CALI				11
#define MSG_COA_MODULE_CALI_RELAY			12
#define MSG_COA_MODULE_SET_TRAY_READY		13
#define MSG_COA_MODULE_BMS_COMM_REQUEST		14
#define MSG_COA_MODULE_DAQ_ISOLATION_REQUEST	15
#define MSG_COA_MODULE_CH_CALI_UPDATE		16
#define MSG_COA_MODULE_CAN_TRANSMIT_CHANGE	17
#define MSG_COA_MODULE_CH_IO_SET			18
#define MSG_COA_MODULE_CMD_CHAMBER_CONTINUE	19 //kjg_101221_s
#define MSG_COA_MODULE_CMD_CABLE_CHECK		20
#define MSG_COA_MODULE_CMD_CELL_CHECK		21
#define MSG_COA_MODULE_CMD_CYCLE_CONTINUE	22 //kjg_101221_e
#define MSG_COA_MODULE_BUZZER_STOP			23
#define MSG_COA_MODULE_ALARM_RESET			24
#define MSG_COA_MODULE_BMS_EOL_DATA1_REQUEST	25
#define MSG_COA_MODULE_BMS_EOL_DATA2_REQUEST	26
#define MSG_COA_MODULE_BMS_EOL_PACK_ID_WRITE	27
#define MSG_COA_MODULE_BMS_EOL_PACK_ID_CHECK	28
#define MSG_COA_MODULE_BMS_EOL_HI_POT_TEST	29
#define MSG_COA_MODULE_BMS_EOL_DATA3_REQUEST	30
#define MSG_COA_MODULE_BMS_EOL_CVTN_ID_REQUEST	31
#define MSG_COA_MODULE_BMS_EOL_DTC_CLEAR	32
#define MSG_COA_MODULE_BMS_EOL_RESET_MICRO	33
#define MSG_COA_MODULE_BMS_EOL_DATA3_LED_REQUEST	34
#define MSG_COA_MODULE_EOL_PROCEDURE_REQUEST	35	//kjg_120709
#define	MSG_COA_MODULE_CALIMODE_REQUEST		36	//jhkw_130119
#define	MSG_COA_MODULE_LOAD_TYPE_SET		37	//kjhw_130129
#define MSG_COA_MODULE_DAQ_ISOLATION_REQUEST2	38	//jhkw_150224
#define MSG_COA_MODULE_OUT_MUX_SELECT_REQUEST	39	//kjhw_151021
#define MSG_COA_MODULE_CMD_GOTO_STEP		40	//kjhw_151211
#define MSG_COA_MODULE_TIMESCH_CMD_NEXT_STEP	41	//kjh_160418
#define MSG_COA_MODULE_BMS_PROCEDURE_REQUEST	42	//kjg_161207
#define MSG_COA_MODULE_CMD_TEST_COND_UPDATE	43 //kjg_170810
#define MSG_COA_MODULE_CAN_OR_LINTOCAN_SET	44 //kjhw_181111
#define MSG_COA_MODULE_CHAMBER_VENT_STOP	45 //kjhw_190820
#define MSG_COA_MODULE_CAP_BANK_SET			46 //kjh_191014
#define MSG_COA_MODULE_GUI_EMG_SET			48 //khj_201227
#define MSG_COA_MODULE_GUI_SHUTDOWN			49 //ktg_250410		//jhj_250410
#define MSG_COA_MODULE_PC_TIME_SYNC			50 //KimJangHun_241002 //shh_250122 SWEGPROD-1488

// 44~ COA?Client to AppControl
#define MSG_COA_APP_PROCESS_KILL			1
#define MSG_COA_APP_WRITE_CH_ATTRIBUTE		2
#define MSG_COA_APP_WRITE_AUX_SET_DATA		3
#define MSG_COA_APP_WRITE_CAN_RECEIVE_SET_DATA	4
#define MSG_COA_APP_WRITE_CAN_TRANSMIT_SET_DATA	5
#define MSG_COA_APP_WRITE_VBF_DATA			6
#define MSG_COA_APP_TEST_COND_CONVERSION_START	7
#define MSG_COA_APP_READ_TH_TABLE_SET		8 //kjhw_181111
#define MSG_COA_APP_READ_HUMIDITY_TABLE_SET		9 //csk_200207
#define MSG_COA_APP_CMD_CALI_TEMP			10		//khj_210802
#define MSG_COA_APP_READ_CAN_TH_TABLE_SET		11 //ktg_220614

// 56~ COA?Client to Meter
#define MSG_COA_METER_INITIALIZE			1

// 48~ COB?Client to Module
#define MSG_COB_MODULE_CMD_RUN				1
#define MSG_COB_MODULE_CMD_STOP				2
#define MSG_COB_MODULE_CMD_PAUSE			3
#define MSG_COB_MODULE_CMD_CONTINUE			4
#define MSG_COB_MODULE_CMD_NEXT_STEP		5
#define MSG_COB_MODULE_CMD_RESET			6
#define MSG_COB_MODULE_CMD_CLEAR			7
#define MSG_COB_MODULE_WORK_MODE			8
#define MSG_COB_MODULE_SAVE_MSG_FLAG		9
#define MSG_COB_MODULE_CMD_SET_BCR_LAMP		10
#define MSG_COB_MODULE_CONTROL_MODE			11
#define MSG_COB_MODULE_JIG_TRY_CONTACT		12
#define MSG_COB_MODULE_JIG_TRY_DISCONTACT	13
#define MSG_COB_MODULE_CALI_METER_INIT		14
#define MSG_COB_MODULE_PLC_DOOR_OPEN		15
#define MSG_COB_MODULE_PLC_DOOR_CLOSE		16
#define MSG_COB_MODULE_PLC_FAULT_READ		17
#define MSG_COB_MODULE_CHAMBER_SET			18
#define MSG_COB_MODULE_CALI_V				19	//kjg_110713
#define MSG_COB_MODULE_CALI_CHECK_V			20
#define MSG_COB_MODULE_CALI_I				21
#define MSG_COB_MODULE_CALI_CHECK_I			22
#define MSG_COB_MODULE_CALI_STOP			23
#define MSG_COB_MODULE_CALI_PAUSE			24
#define MSG_COB_MODULE_CALI_RESUME			25
#define MSG_COB_MODULE_CALI_DAV				26
#define MSG_COB_MODULE_CALI_CHECK_DAV		27
#define MSG_COB_MODULE_CALI_DAI				28
#define MSG_COB_MODULE_CALI_CHECK_DAI		29
#define MSG_COB_MODULE_CALI_V_RANGE			30
#define MSG_COB_MODULE_CALI_I_RANGE			31
#define MSG_COB_MODULE_CALI_MULTI			32
#define MSG_COB_MODULE_CALI_MAP				33
#define MSG_COB_MODULE_REAL_MEASURE_V		34
#define MSG_COB_MODULE_REAL_MEASURE_I		35
#define MSG_COB_MODULE_MEAS					36
#define MSG_COB_MODULE_MEASURE_STOP			37
#define MSG_COB_MODULE_MEASURE_TIME			38
#define MSG_COB_MODULE_CMD_BUZZER_OFF		39

// 44~ COB?Client to AppControl
#define MSG_COB_APP_PROCESS_KILL			1
#define MSG_COB_APP_CALI_UPDATE				2 //kjg_110713
#define MSG_COB_APP_WRITE_CH_ATTRIBUTE		3

// 56~ COB?Client to Meter
#define MSG_COB_METER_INITIALIZE			1

// 68~ COB?Client to Jig?Control
#define MSG_COB_JIGC_JOB_CHANGE				1
#define MSG_COB_JIGC_TRY_CONTACT			2
#define MSG_COB_JIGC_TRY_DISCONTACT			3
#define MSG_COB_JIGC_PITCH_CHANGE			4

// 40~ COA?Client to Module
#define MSG_COC_MODULE_CMD_RUN				1
#define MSG_COC_MODULE_CMD_STOP				2
#define MSG_COC_MODULE_CMD_PAUSE			3
#define MSG_COC_MODULE_CMD_CONTINUE			4
#define MSG_COC_MODULE_CMD_NEXT_STEP		5
#define MSG_COC_MODULE_CMD_RESET			6
#define MSG_COC_MODULE_CMD_CLEAR			7
#define MSG_COC_MODULE_WORK_MODE			8
#define MSG_COC_MODULE_SAVE_MSG_FLAG		9
#define MSG_COC_MODULE_CMD_CHECK			10
#define MSG_COC_MODULE_CH_CALI				11
#define MSG_COC_MODULE_CALI_RELAY			12
#define MSG_COC_MODULE_SET_TRAY_READY		13
#define MSG_COC_MODULE_BMS_COMM_REQUEST		14
#define MSG_COC_MODULE_DAQ_ISOLATION_REQUEST	15
#define MSG_COC_MODULE_CH_CALI_UPDATE		16
#define MSG_COC_MODULE_CMD_INIT				17
#define MSG_COC_MODULE_CMD_CHAMBER_CONTINUE	18
#define MSG_COC_MODULE_CMD_CABLE_CHECK		19
#define MSG_COC_MODULE_CMD_CELL_CHECK		20
#define MSG_COC_MODULE_CMD_CYCLE_CONTINUE	21

// 44~ COA?Client to AppControl
#define MSG_COC_APP_PROCESS_KILL			1
#define MSG_COC_APP_WRITE_CH_ATTRIBUTE		2
#define MSG_COC_APP_WRITE_AUX_SET_DATA		3
#define MSG_COC_APP_WRITE_CAN_RECEIVE_SET_DATA	4
#define MSG_COC_APP_WRITE_CAN_TRANSMIT_SET_DATA	5

// 56~ COA?Client to Meter
#define MSG_COC_METER_INITIALIZE			1

//Jig?Control to COB
#define MSG_JIGC_COB_JOB_CHANGE_END			1

// 60~ Jig?Control to ioControl
#define MSG_JIGC_IO_OUT_BIT					1
#define MSG_JIGC_IO_EMG						2
#define MSG_JIGC_IO_OUT_BLINK				3
#define MSG_JIGC_IO_READ_BCR				4

// 64~ Jig?Control to JigManager
#define MSG_JIGC_JIGM_FAIL					1
#define MSG_JIGC_JIGM_CONTACT_COMPLETE		2
#define MSG_JIGC_JIGM_DISCONTACT_COMPLETE	3
#define MSG_JIGC_JIGM_START_BUTTON			4
#define MSG_JIGC_JIGM_STOP_BUTTON			5
#define MSG_JIGC_JIGM_CONTINUE_BUTTON		6
#define MSG_JIGC_JIGM_EMG_BUTTON			7
#define MSG_JIGC_JIGM_READ_BCR				8

// 70~ JigManager to Jig?Control
#define MSG_JIGM_JIGC_TRY_CONTACT			1
#define MSG_JIGM_JIGC_TRY_DISCONTACT		2
#define MSG_JIGM_JIGC_TRY_TRAY_CHECK		3
#define MSG_JIGM_JIGC_SET_TRAY_READY		4
#define MSG_JIGM_JIGC_LAMP					5
#define MSG_JIGM_JIGC_DOOR_OPEN				6
#define MSG_JIGM_JIGC_DOOR_CLOSE			7
#define MSG_JIGM_JIGC_PLC_ALARM_AREA_SENSOR	8
#define MSG_JIGM_JIGC_PLC_ALARM_MANUAL_DOOR_OPEN	9
#define MSG_JIGM_JIGC_PLC_ALARM_AIR			10
#define MSG_JIGM_JIGC_PLC_ALARM_APR_S		11
#define MSG_JIGM_JIGC_PLC_ALARM_REF			12
#define MSG_JIGM_JIGC_PLC_ALARM_COIL_TRIP	13
#define MSG_JIGM_JIGC_PLC_ALARM_TEMP		14
#define MSG_JIGM_JIGC_PLC_ALARM_SMOKE		15
#define MSG_JIGM_JIGC_PLC_ALARM_FIRE		16
#define MSG_JIGM_JIGC_PLC_ALARM_EMG			17

// 75 JigManager to Module
#define MSG_JIGM_MODULE_CONTACT_COMPLETE	1
#define MSG_JIGM_MODULE_DISCONTACT_COMPLETE	2
#define MSG_JIGM_MODULE_FAIL				3
#define MSG_JIGM_MODULE_START_BUTTON		4
#define MSG_JIGM_MODULE_STOP_BUTTON			5
#define MSG_JIGM_MODULE_CONTINUE_BUTTON		6
#define MSG_JIGM_MODULE_EMG_SWITCH			7

// 80 ioControl to Module
#define MSG_IO_MODULE_EXIT					1
#define MSG_IO_MODULE_CH_PAUSE				2	//csk_190620

// 85 ioControl to AppControl
#define MSG_IO_APP_POWER_OFF_BUTTON			1	//csk_200113

// 90 Module to AppControl
#define MSG_MODULE_APP_EXIT					1
#define MSG_MODULE_APP_PROCESS_KILL			2
#define MSG_MODULE_APP_CALI_DA_END			3 //kjg_110814
#define MSG_MODULE_APP_CALI_END				4 //kjg_110814
#define MSG_MODULE_APP_FAULT_HW_CURRENT     5
#define MSG_MODULE_APP_CAN_DATA_DEBUG		6 //kjg_141114
#define MSG_MODULE_APP_WRITE_CH_ATTRIBUTE	7 //kjhw_150216
#define MSG_MODULE_APP_FAULT_HW_OC			8	//jhkw_170917s
#define MSG_MODULE_APP_FAULT_HW_DCOV		9
#define MSG_MODULE_APP_FAULT_HW_MOD_FAULT	10	//jhkw_170917e

// 91 Module to DataSave
#define MSG_MODULE_DATASAVE_RCVED_CMD_RUN	1
#define MSG_MODULE_DATASAVE_RCVED_CMD_CONTINUE	2
#define MSG_MODULE_DATASAVE_READ_PATTERN_FILE	3
#define MSG_MODULE_DATASAVE_CALI_VALUE		4
#define MSG_MODULE_DATASAVE_CREATE_RUN_FILE	5
#define MSG_MODULE_DATASAVE_DELETE_RUN_FILE	6
#define MSG_MODULE_DATASAVE_READ_USERMAP_FILE	7 //kjhw_140828

#define MSG_MODULE_DATASAVE_CALI_NORMAL_RESULT_SAVE	11
#define MSG_MODULE_DATASAVE_CALI_CHECK_RESULT_SAVE	12

#define MSG_MODULE_DATASAVE_SAVED_FILE_DELETE_TRY	21
#define MSG_MODULE_DATASAVE_SAVED_FILE_DELETE_TRY_LG	22

// 92~ Module to COA?Client
#define MSG_MODULE_COA_TROUBLE_CODE			1
#define MSG_MODULE_COA_GROUP_STATE_ERROR	2
#define MSG_MODULE_COA_BMS_COMM_END			3
#define MSG_MODULE_COA_OUT_PACK_ISOLATION	4
#define MSG_MODULE_COA_BMS_EOL_DATA1_REPLY	5
#define MSG_MODULE_COA_BMS_EOL_DATA2_REPLY	6
#define MSG_MODULE_COA_BMS_EOL_PACK_ID_WRITE_REPLY	7
#define MSG_MODULE_COA_BMS_EOL_PACK_ID_CHECK_REPLY	8
#define MSG_MODULE_COA_BMS_EOL_HI_POT_TEST_REPLY	9
#define MSG_MODULE_COA_EMG_STATUS			10
#define MSG_MODULE_COA_DAQ_ISOLATION_REPLY	11
#define MSG_MODULE_COA_BMS_EOL_DATA3_REPLY	12
#define MSG_MODULE_COA_BMS_EOL_CVTN_ID_REPLY	13
#define MSG_MODULE_COA_CABLE_CHECK_REPLY	14	//kjg_120709_w
#define MSG_MODULE_COA_CELL_CHECK_REPLY		15	//kjg_120709_w
#define MSG_MODULE_COA_EOL_PROCEDURE_REPLY	16	//kjg_120709
#define MSG_MODULE_COA_CAN_CABLE_BAD		17	//kjg_120709
#define MSG_MODULE_COA_DAQ_ISOLATION_REPLY2	18	//jhkw_150224
#define MSG_MODULE_COA_OUT_MUX_SELECT_REPLY	19	//kjhw_151021
#define MSG_MODULE_COA_BMS_PROCEDURE_REPLY	20	//kjg_161207

// 96~ Module to COB?Client
#define MSG_MODULE_COB_TROUBLE_CODE			1
#define MSG_MODULE_COB_GROUP_STATE_ERROR	2
#define MSG_MODULE_LG_TROUBLE_CODE			3
#define MSG_MODULE_LG_POWER_OFF_PROCESS		4
#define MSG_MODULE_COB_START				5
#define MSG_MODULE_COB_STOP					6
#define MSG_MODULE_COB_RESET				7
#define MSG_MODULE_COB_PAUSE				8
#define MSG_MODULE_COB_CONTINUE				9
#define MSG_MODULE_COB_WORK_MODE			10
#define MSG_MODULE_COB_CONTROL_MODE			11
#define MSG_MODULE_COB_RESET_COMPLETE		12
#define MSG_MODULE_COB_SEND_GROUP_STATE		13
#define MSG_MODULE_COB_TRAY_ID				14
#define MSG_MODULE_COB_JIG_FUNCTION			15

#define MSG_MODULE_COB_CALI_DATA			16 //kjg_110816_s
#define MSG_MODULE_COB_CALI_END				17
#define MSG_MODULE_COB_CALI_CHECK_DATA		18
#define MSG_MODULE_COB_CALI_CHECK_END		19
#define MSG_MODULE_COB_REAL_MEASURE_DATA	20
#define MSG_MODULE_COB_REAL_MEASURE_END		21 //kjg_110816_e

// 92~ Module to COC?Client
#define MSG_MODULE_COC_TROUBLE_CODE			1
#define MSG_MODULE_COC_GROUP_STATE_ERROR	2
//kjg_130417 #define MSG_MODULE_COC_BMS_COMM_END			3
#define MSG_MODULE_COC_CABLE_CHECK_REPLY	4
#define MSG_MODULE_COC_CELL_CHECK_REPLY		5
#define MSG_MODULE_COC_EMG_STATUS			11

// 100 Module to JigManager
#define MSG_MODULE_JIGM_TRY_CONTACT 		1
#define MSG_MODULE_JIGM_TRY_DISCONTACT 		2
#define MSG_MODULE_JIGM_LAMP		 		3
#define MSG_MODULE_JIGM_DOOR_OPEN			4
#define MSG_MODULE_JIGM_DOOR_CLOSE	 		5
#define MSG_MODULE_JIGM_PLC_ALARM_AREA_SENSOR	6
#define MSG_MODULE_JIGM_PLC_ALARM_MANUAL_DOOR_OPEN	7
#define MSG_MODULE_JIGM_PLC_ALARM_AIR		8
#define MSG_MODULE_JIGM_PLC_ALARM_APR_S		9
#define MSG_MODULE_JIGM_PLC_ALARM_REF		10
#define MSG_MODULE_JIGM_PLC_ALARM_COIL_TRIP	11
#define MSG_MODULE_JIGM_PLC_ALARM_TEMP		12
#define MSG_MODULE_JIGM_PLC_ALARM_SMOKE		13
#define MSG_MODULE_JIGM_PLC_ALARM_FIRE		14
#define MSG_MODULE_JIGM_PLC_ALARM_EMG		15

// Module to TimeSchedule
#define MSG_MODULE_TIMESCH_INITIALIZE		1 //kjh_160418

// TimeSchedule to COA
#define MSG_TIMESCH_COA_CMD_NEXT_STEP		1 //kjh_160418

// 101 Module to ioControl
#define MSG_MODULE_IO_EXIT					1
#define MSG_MODULE_IO_RUN_LED				2
#define MSG_MODULE_IO_REMOTE_PS				3

// 102 Module to Meter
#define MSG_MODULE_METER_REQUEST			1

// 120~ Meter to COA?Client
#define MSG_METER_COA_INITIALIZE_REPLY		1

// 120~ Meter to COB?Client
#define MSG_METER_COB_INITIALIZE_REPLY		1

// 120~ Meter to COC?Client
#define MSG_METER_COC_INITIALIZE_REPLY		1

// 128 Meter to Module
#define MSG_METER_MODULE_REQUEST_REPLY		1

// 1 Upadte_Process to ioControl
#define MSG_UPDATE_IO_EXIT					1

//f_save message direction
#define SAVE_GROUP1_TO_DATASAVE				0
#define SAVE_GROUP2_TO_DATASAVE				1
#define SAVE_GROUP3_TO_DATASAVE				2
#define SAVE_GROUP4_TO_DATASAVE				3
#define SAVE_GROUP_TO_COB1					4
#define SAVE_GROUP_TO_COB2					5
#define SAVE_GROUP_TO_COB3					6
#define SAVE_GROUP_TO_COB4					7
#define SAVE_GROUP_TO_COC1					8
#define SAVE_GROUP_TO_COC2					9
#define SAVE_GROUP_TO_COC3					10
#define SAVE_GROUP_TO_COC4					11

//real data save message direction
#define SAVE_GROUP1_TO_REAL_DATASAVE		0
#define SAVE_GROUP2_TO_REAL_DATASAVE		1
#define SAVE_GROUP3_TO_REAL_DATASAVE		2
#define SAVE_GROUP4_TO_REAL_DATASAVE		3

//send dcir message direction
#define SAVE_DCIR_GROUP_TO_COB1				0
#define SAVE_DCIR_GROUP_TO_COB2				1
#define SAVE_DCIR_GROUP_TO_COB3				2
#define SAVE_DCIR_GROUP_TO_COB4				3
#endif
