#ifndef __TIMESCHEDULE_DEF_H__
#define __TIMESCHEDULE_DEF_H__

// Load_Process
//#define PROCESS_TIME_SCHEDULE				2 //kjhw_160418

// AppControl Signal
//#define APP_SIG_TIME_SCHEDULE_PROCESS		9 //kjh_160418

//#define APP_SIG_TIME_SCHEDULE_PROCESS_CHECK	59 //kjhw_160418
#define TIMESCH_SIG_TIMESCH_INITIALIZE_1	1
#define TIMESCH_SIG_TIMESCH_INITIALIZE_2	2
#define TIMESCH_SIG_TIMESCH_INITIALIZE_3	3
#define TIMESCH_SIG_TIMESCH_INITIALIZE_4	4
#define TIMESCH_SIG_TIMESCH_INITIALIZE_5	5
#define TIMESCH_SIG_TIMESCH_INITIALIZE_6	6
#define TIMESCH_SIG_TIMESCH_INITIALIZE_7	7
#define TIMESCH_SIG_TIMESCH_INITIALIZE_8	8
#define TIMESCH_SIG_TIMESCH_INITIALIZE_9	9
#define TIMESCH_SIG_TIMESCH_INITIALIZE_10	10

#endif
