#ifndef __INOUTCONTROL_DEF_H__
#define __INOUTCONTROL_DEF_H__

#define BITS_PER_BYTE				8

#define MAX_DIO_II_BYTES			8
#define MAX_DIO_IO_BYTES			8
#define MAX_DIO_MI_BYTES			8
#define MAX_DIO_MO_BYTES			8
#define MAX_DIO_CI_BYTES			8
#define MAX_DIO_CO_BYTES			8
#define MAX_DIO_EI_BYTES			8
#define MAX_DIO_EO_BYTES			8

#define MAX_DIO_IN_BYTES			(MAX_DIO_II_BYTES + MAX_DIO_MI_BYTES + MAX_DIO_CI_BYTES + MAX_DIO_EI_BYTES)
#define MAX_DIO_OUT_BYTES			(MAX_DIO_IO_BYTES + MAX_DIO_MO_BYTES + MAX_DIO_CO_BYTES + MAX_DIO_EO_BYTES)

#define MAX_DIO_IN_FUNCTION			(MAX_DIO_IN_BYTES * BITS_PER_BYTE)
#define MAX_DIO_OUT_FUNCTION		(MAX_DIO_OUT_BYTES * BITS_PER_BYTE)

//digital io signal
#define DIO_SIG_POWER_SWITCH		0
#define DIO_SIG_MAIN_EMG			1
#define DIO_SIG_SUB_EMG				2
#define DIO_SIG_POWER_FAIL			3
#define DIO_SIG_PS_FAIL				4
#define DIO_SIG_REMOTE_PS			5
#define DIO_SIG_RIPPLE_SWITCH		6
#define DIO_SIG_CABLE_FAIL1			7
#define DIO_SIG_CABLE_FAIL2			8
#define DIO_SIG_CABLE_FAIL3			9
#define DIO_SIG_CABLE_FAIL4			10
#define DIO_SIG_CABLE_FAIL5			11
#define DIO_SIG_CABLE_FAIL6			12
#define DIO_SIG_CABLE_FAIL7			13
#define DIO_SIG_CABLE_FAIL8			14
#define DIO_SIG_IN_EXTERNAL1		15
#define DIO_SIG_IN_EXTERNAL2		16
#define DIO_SIG_IN_START1			17
#define DIO_SIG_IN_STOP1			18
#define DIO_SIG_IN_START2			19
#define DIO_SIG_IN_STOP2			20
#define DIO_SIG_FAN_ERROR			21		//phb_221223 //shh_230607
//#define DIO_SIG_FAN_FAIL			21
#define DIO_SIG_PNE_AC_POWER_FAIL	22
#define DIO_SIG_PNE_AC_POWER_DETECT	23
#define DIO_SIG_PNE_AC_POWER_DETECT2	24
#define DIO_SIG_IN_CHARGER_WAKEUP	25
#define DIO_SIG_IN_CHARGER_PHASE	26
#define DIO_SIG_UPS_BATTERY_FAIL	27
#define DIO_SIG_CHAMBER_EMG_FAIL	28
#define DIO_SIG_CHAMBER_POWER_FAIL	29
#define DIO_SIG_CHAMBER_POWER_FAIL2	30
#define DIO_SIG_CHAMBER_DOOR_OPEN_FAIL	31
#define DIO_SIG_CHAMBER_OVER_TEMP_FAIL	32
#define DIO_SIG_CHAMBER_AIR_FAIL	33
#define DIO_SIG_CHAMBER_EOCR_FAIL	34
#define DIO_SIG_CHAMBER_FAN_FAIL	35
#define DIO_SIG_CHAMBER_FIRE_FAIL	36
#define DIO_SIG_CHAMBER_SMOKE_FAIL	37
#define DIO_SIG_CHAMBER_REF_FAIL	38
#define DIO_SIG_CHAMBER_LEAK_FAIL	39 //lki_111010_s
#define DIO_SIG_CHAMBER_CP_TRIP_FAIL	40
#define DIO_SIG_CHAMBER_EMG_FAIL_2	41
#define DIO_SIG_CHAMBER_OVER_TEMP_FAIL_2	42
#define DIO_SIG_CHAMBER_AIR_FAIL_2	43
#define DIO_SIG_CHAMBER_EOCR_FAIL_2	44
#define DIO_SIG_CHAMBER_FIRE_FAIL_2	45
#define DIO_SIG_CHAMBER_LEAK_FAIL_2	46
#define DIO_SIG_CHAMBER_CP_TRIP_FAIL_2	47
#define DIO_SIG_CHAMBER_POWER_FAIL_2	48 //lki_111010_e
#define DIO_SIG_EXT_OT_FAIL			49	//jhkw_160219

#define DIO_SIG_FUSE_FAIL1			51
#define DIO_SIG_FUSE_FAIL2			52
#define DIO_SIG_FUSE_FAIL3			53
#define DIO_SIG_FUSE_FAIL4			54
#define DIO_SIG_FUSE_FAIL5			55
#define DIO_SIG_FUSE_FAIL6			56
#define DIO_SIG_FUSE_FAIL7			57
#define DIO_SIG_FUSE_FAIL8			58
#define DIO_SIG_UPPER_VOLTAGE1		59
#define DIO_SIG_UPPER_VOLTAGE2		60
#define DIO_SIG_UPPER_VOLTAGE3		61
#define DIO_SIG_UPPER_VOLTAGE4		62
#define DIO_SIG_UPPER_VOLTAGE5		63
#define DIO_SIG_UPPER_VOLTAGE6		64
#define DIO_SIG_UPPER_VOLTAGE7		65
#define DIO_SIG_UPPER_VOLTAGE8		66
#define DIO_SIG_LOWER_VOLTAGE1		67
#define DIO_SIG_LOWER_VOLTAGE2		68
#define DIO_SIG_LOWER_VOLTAGE3		69
#define DIO_SIG_LOWER_VOLTAGE4		70
#define DIO_SIG_LOWER_VOLTAGE5		71
#define DIO_SIG_LOWER_VOLTAGE6		72
#define DIO_SIG_LOWER_VOLTAGE7		73
#define DIO_SIG_LOWER_VOLTAGE8		74
#define DIO_SIG_OT1					75
#define DIO_SIG_OT2					76
#define DIO_SIG_OT3					77
#define DIO_SIG_OT4					78
#define DIO_SIG_OT5					79
#define DIO_SIG_OT6					80
#define DIO_SIG_OT7					81
#define DIO_SIG_OT8					82
#define DIO_SIG_POWER_TRANS_OT1		83
#define DIO_SIG_POWER_TRANS_OT2		85
#define DIO_SIG_POWER_TRANS_OT3		86
#define DIO_SIG_POWER_TRANS_OT4		87
#define DIO_SIG_POWER_TRANS_OT5		88
#define DIO_SIG_POWER_TRANS_OT6		89
#define DIO_SIG_POWER_TRANS_OT7		90
#define DIO_SIG_POWER_TRANS_OT8		91
#define DIO_SIG_POWER_REACTOR_OT1	92
#define DIO_SIG_POWER_REACTOR_OT2	93
#define DIO_SIG_POWER_REACTOR_OT3	94
#define DIO_SIG_POWER_REACTOR_OT4	95
#define DIO_SIG_POWER_REACTOR_OT5	96
#define DIO_SIG_POWER_REACTOR_OT6	97
#define DIO_SIG_POWER_REACTOR_OT7	98
#define DIO_SIG_POWER_REACTOR_OT8	99
#define DIO_SIG_MAIN_PS_R1			100
#define DIO_SIG_MAIN_PS_R2			101
#define DIO_SIG_MAIN_PS_R3			102
#define DIO_SIG_MAIN_PS_R4			103
#define DIO_SIG_MAIN_PS_R5			104
#define DIO_SIG_MAIN_PS_R6			105
#define DIO_SIG_MAIN_PS_R7			106
#define DIO_SIG_MAIN_PS_R8			107
#define DIO_SIG_MAIN_PS_S1			108
#define DIO_SIG_MAIN_PS_S2			109
#define DIO_SIG_MAIN_PS_S3			110
#define DIO_SIG_MAIN_PS_S4			111
#define DIO_SIG_MAIN_PS_S5			112
#define DIO_SIG_MAIN_PS_S6			113
#define DIO_SIG_MAIN_PS_S7			114
#define DIO_SIG_MAIN_PS_S8			115
#define DIO_SIG_MAIN_PS_T1			116
#define DIO_SIG_MAIN_PS_T2			117
#define DIO_SIG_MAIN_PS_T3			118
#define DIO_SIG_MAIN_PS_T4			119
#define DIO_SIG_MAIN_PS_T5			120
#define DIO_SIG_MAIN_PS_T6			121
#define DIO_SIG_MAIN_PS_T7			122
#define DIO_SIG_MAIN_PS_T8			123
#define DIO_SIG_MCCB_FAIL1			124 //lki_111010
#define DIO_SIG_CHAMBER_FIRE_FAIL_3	125	//jhkw_191216s
#define DIO_SIG_CHAMBER_FIRE_FAIL_4	126
#define DIO_SIG_CHAMBER_EMG_FAIL_3	127
#define DIO_SIG_CHAMBER_EMG_FAIL_4	128
#define DIO_SIG_CHAMBER_ETC_FAIL	129
#define DIO_SIG_CHAMBER_ETC_FAIL_2	130
#define DIO_SIG_CHAMBER_ETC_FAIL_3	131
#define DIO_SIG_CHAMBER_ETC_FAIL_4	132
#define DIO_SIG_CHAMBER_DOOR_OPEN_FAIL_2	133
#define DIO_SIG_CHAMBER_DOOR_OPEN_FAIL_3	134
#define DIO_SIG_CHAMBER_DOOR_OPEN_FAIL_4	135	//jhkw_191216e
#define DIO_SIG_CHAMBER_SMOKE_FAIL_2	136
#define DIO_SIG_CHAMBER_SMOKE_FAIL_3	137
#define DIO_SIG_CHAMBER_SMOKE_FAIL_4	138
#define DIO_SIG_DC_LINK_FUSE_FAIL1	139
#define DIO_SIG_DC_LINK_FUSE_FAIL2	140
#define DIO_SIG_DC_LINK_FUSE_FAIL3	141
#define DIO_SIG_DC_LINK_FUSE_FAIL4	142

typedef enum {
	I_SPARE=0,

	I_POWER_SWITCH,
	I_EMG_SWITCH,
	I_AC_POWER_FAIL,
	I_UPS_BATTERY_FAIL,
	I_NO_POWER_OFF,
	I_PS_FAIL,
	I_FAN_ERROR,		//phb_221223 //shh_230607
	//I_FAN_FAIL,

	I_FUSE_FAIL,
	I_MAIN_MC,
	I_SUB_MC,
	I_INVERTER_HV_FAULT,
	I_INVERTER_MODULE_R_FAIL,
	I_INVERTER_MODULE_S_FAIL,
	I_INVERTER_MODULE_T_FAIL,
	I_INVERTER_PRE_CHARGE,
	I_INVERTER_OT,
	I_INVERTER_RUN,
	I_POWER_TRANS_OT,
	I_POWER_REACTOR_OT,
	I_MCCB_FAIL,
	I_INVERTER_OC,
	I_INVERTER_ETC,

	I_PS1_FAIL,
	I_PS2_FAIL,
	I_PS3_FAIL,
	I_PS4_FAIL,
	I_PS5_FAIL,
	I_PS6_FAIL,
	I_PS7_FAIL,
	I_PS8_FAIL,
	I_PS9_FAIL,
	I_PS10_FAIL,
	I_PS11_FAIL,
	I_PS12_FAIL,
	I_PS13_FAIL,
	I_PS14_FAIL,
	I_PS15_FAIL,
	I_PS16_FAIL,
	I_OT1_FAIL,
	I_OT2_FAIL,
	I_OT3_FAIL,
	I_OT4_FAIL,
	I_OT5_FAIL,
	I_OT6_FAIL,
	I_OT7_FAIL,
	I_OT8_FAIL,
	I_OT9_FAIL,
	I_OT10_FAIL,
	I_OT11_FAIL,
	I_OT12_FAIL,
	I_OT13_FAIL,
	I_OT14_FAIL,
	I_OT15_FAIL,
	I_OT16_FAIL,

	I_SUB_EMG,
	I_CONVERTER_OV,
	I_CONVERTER_OC,
	I_CONVERTER_DCOV,
	I_CONVERTER_MODULE_FAULT,
	I_CONVERTER_OC_2,   //jhkw_170917s
	I_CONVERTER_OC_3,
	I_CONVERTER_OC_4,
	I_CONVERTER_DCOV_2,
	I_CONVERTER_MODULE_F_2,
	I_CONVERTER_MODULE_F_3,
	I_CONVERTER_MODULE_F_4, //jhkw_170917e
	I_CONVERTER_OT,
	I_RANGE_FAULT,
	I_CONVERTER_IN_FUSE_FAIL,

	I_I_RANGE1,
	I_I_RANGE2,
	I_I_RANGE3,
	I_I_RANGE4,
	I_PARALLEL,
	I_PARALLEL_SUB, //kjhw_150120
	I_RIPPLE_SWITCH,
	I_MODE_CV_DETECT,
	I_OUT_FUSE_FAIL,
	I_OUT_REACTOR_OT,
	I_OUT_PACK_ISOLATION,
	//jhkw_150224s
	I_OUT_PACK_ISOLATION2,
	I_OUT_PACK_ISOLATION3,
	I_OUT_PACK_ISOLATION4,
	I_OUT_PACK_ISOLATION5,
	I_OUT_PACK_ISOLATION6,
	//jhkw_150224e
	
	I_RUN_RELAY, //kjhw_150120
	I_RUN_RELAY_SUB, //kjhw_150120

	I_CABLE_FAIL,

	I_EXTERNAL1,
	I_EXTERNAL2,
	I_EXTERNAL3,
	I_EXTERNAL4,
	I_EXTERNAL5,
	I_EXTERNAL6,
	I_EXTERNAL7,
	I_EXTERNAL8,

	I_CHARGER_WAKEUP,
	I_PACK_SIGNAL,

	I_JIG_LATCH_CYLINDER_L_ON_OFF,
	I_JIG_LATCH_CYLINDER_L_ON,
	I_JIG_LATCH_CYLINDER_L_OFF,
	I_JIG_LATCH_CYLINDER_R_ON_OFF,
	I_JIG_LATCH_CYLINDER_R_ON,
	I_JIG_LATCH_CYLINDER_R_OFF,
	I_JIG_MAIN_CYLINDER_L_ON_OFF,
	I_JIG_MAIN_CYLINDER_L_ON,
	I_JIG_MAIN_CYLINDER_L_OFF,
	I_JIG_MAIN_CYLINDER_R_ON_OFF,
	I_JIG_MAIN_CYLINDER_R_ON,
	I_JIG_MAIN_CYLINDER_R_OFF,
	I_JIG_GRIP_CYLINDER_L_ON_OFF,
	I_JIG_GRIP_CYLINDER_L_ON,
	I_JIG_GRIP_CYLINDER_L_OFF,
	I_JIG_GRIP_CYLINDER_R_ON_OFF,
	I_JIG_GRIP_CYLINDER_R_ON,
	I_JIG_GRIP_CYLINDER_R_OFF,
	I_JIG_STOPPER_STATE,
	I_JIG_TRAY_STATE,
	I_JIG_AIR_PRESS,
	I_JIG_SW_DOWN,
	I_JIG_SW_UP,
	I_JIG_SW_START,
	I_JIG_SW_STOP,
	I_JIG_SW_EMG,
	I_JIG_SMOKE_SENS,
	I_JIG_FIRE_SENS,
	I_JIG_OT_SENS,
	I_JIG_STACKER_STATE,
	I_JIG_ROLL_L_F_ON,
	I_JIG_ROLL_L_F_OFF,
	I_JIG_ROLL_L_R_ON,
	I_JIG_ROLL_L_R_OFF,
	I_JIG_ROLL_R_F_ON,
	I_JIG_ROLL_R_F_OFF,
	I_JIG_ROLL_R_R_ON,
	I_JIG_ROLL_R_R_OFF,
	I_JIG_CHAMBER_FIRE,
	I_JIG_CHAMBER_SMOKE,
	I_JIG_CHAMBER_DOOR_OPEN,
	I_JIG_CHAMBER_OVER_TEMP,
	I_JIG_CHAMBER_AIR_PRESS,
	I_JIG_CHAMBER_EMG,
	I_JIG_CHAMBER_EOCR,
	I_JIG_CHAMBER_FAN,
	I_JIG_CHAMBER_RUN_MODE,
	I_JIG_CHAMBER_POWER,
	I_JIG_CHAMBER_REF_ERROR,
	I_JIG_CHAMBER_CP_TRIP,
	I_JIG_CHAMBER_LEAK,
	I_JIG_CHAMBER_ETC,	//jhkw_191216
	I_JIG_EXT_OT,	//jhkw_160219
	I_JIG_CHANGE_X,
	I_JIG_CHANGE_Y,
	I_JIG_CHANGE_Z,
	I_JIG_CHANGE_LOCK,
	I_JIG_PITCH,

	I_MOTOR,
	I_MOTOR_RUN,
	I_MOTOR_ERROR,
	I_MOTOR_READY,
	I_MOTOR_HOME,

	I_REMOTE_CONTROL,
	I_CHAMBER_FAULT,

	I_OUT_CONCENT1, //jhkw_130319s
	I_OUT_CONCENT2,
	I_OUT_CONCENT3,
	I_OUT_CONCENT4, //jhkw_130319e
	I_OUT_CONCENT5,	//jhkw_161113
	I_OUT_CONCENT6,	//jhkw_161113
	I_OUT_CONCENT7,	//jhkw_180206
	I_OUT_CONCENT8,	//jhkw_180206

	I_MUX_A_P, //kjhw_151021s
	I_MUX_A_N,
	I_MUX_B_P,
	I_MUX_B_N, //kjhw_151021e

	I_TEST_01,		//kjhw_150401
	I_TEST_02,		//kjhw_150401
	I_TEST_03,		//kjhw_150401
	I_TEST_04,		//kjhw_150401

	I_FAN_MC_FAIL,	//phb_221221 //shh_230607
	I_DC_LINK_FUSE_FAIL		//phb_230710

} in_function_no;

typedef enum {
	O_SPARE=0,

	O_LOGIC_TYPE, //kjg_logic_type_140324
	O_RUN_LED,
	O_POWER_OFF,
	O_FORCE_POWER_OFF,

	O_PS1,
	O_PS2,
	O_PS3,
	O_PS4,
	O_PS5,
	O_PS6,
	O_PS7,
	O_PS8,
	O_FAN1,
	O_FAN2,
	O_FAN3,
	O_FAN4,
	O_FAN5,
	O_FAN6,
	O_FAN7,
	O_FAN8,

	O_MAIN_MC,
	O_SUB_MC,
	O_INVERTER_RUN,
	O_INVERTER_RUN2,
	O_INVERTER_RESET,
	O_MAIN_MC_IN,
	O_SUB_MC_IN,

	O_RUN_RELAY,
	O_RUN_RELAY_SUB, //kjhw_150120
	O_V_RANGE1,
	O_V_RANGE2,
	O_V_RANGE3,
	O_V_RANGE4,
	O_I_RANGE1,
	O_I_RANGE2,
	O_I_RANGE3,
	O_I_RANGE4,
	O_PARALLEL,
	O_PARALLEL_SUB, //kjhw_150120
	O_PARALLEL_BD, //kjhw_170630
	O_LAMP_CHARGE,
	O_LAMP_DISCHARGE,
	O_LAMP_RUN,

	O_CONVERTER_RUN,
	O_CONVERTER_RESET,
	O_CONVERTER_CHARGE,
	O_CONVERTER_DISCHARGE,
	O_SELECT_VO_VS,
		//O_SELECT_VO_VS : C_SBL_150V_250A_10A_38KW, 75KW_4, 75KW_5 -> H/L 0
	O_SELECT_VREF,
	O_SELECT_V_CALI_PI, //kjhw_130118
	O_LAMP_RIPPLE_ON,
	O_RIPPLE_ON,
	O_CONVERTER_FAIL,
	O_OUT_PRE_CHARGE,
	O_OUT_CAPACITOR,
	O_OUT_PACK_ISOLATION,
	//jhkw_150224s
	O_OUT_PACK_ISOLATION2,
	O_OUT_PACK_ISOLATION3,
	O_OUT_PACK_ISOLATION4,
	O_OUT_PACK_ISOLATION5,
	O_OUT_PACK_ISOLATION6,
	//jhkw_150224e
	O_OUT_VS_ISOLATION,
	O_OUT_VP_ISOLATION,
	O_OUT_VB_ISOLATION,
	O_OUT_VIN_ISOLATION,

	O_EXTERNAL1,
	O_EXTERNAL2,
	O_EXTERNAL3,
	O_EXTERNAL4,
	O_EXTERNAL5,
	O_EXTERNAL6,
	O_EXTERNAL7,
	O_EXTERNAL8,

	O_PACK_SIGNAL,

	O_TOWER_LAMP_RED,
	O_TOWER_LAMP_AMBER,
	O_TOWER_LAMP_GREEN,
	O_TOWER_LAMP_BLUE,
	O_TOWER_LAMP_BUZZER,
	O_LED_RED,
	O_LED_AMBER,
	O_LED_GREEN,

	O_CALI_CHARGE_RELAY,
	O_CALI_DISCHARGE_RELAY,
	O_CALI_SW_1,
	O_CALI_SW_2,
	O_CALI_SW_3,
	O_CALI_SW_4,
	O_CALI_SW_5,
	O_CALI_SW_6,
	O_CALI_SW_7,
	O_CALI_SW_8,
	O_CALI_VP_VB,
	O_CALI_MODE,	//jhkw_130121

	O_JIG_FAN_RELAY,
	O_JIG_LATCH_CYLINDER_ON_OFF,
	O_JIG_LATCH_CYLINDER_ON,
	O_JIG_LATCH_CYLINDER_OFF,
	O_JIG_MAIN_CYLINDER_ON_OFF,
	O_JIG_MAIN_CYLINDER_ON,
	O_JIG_MAIN_CYLINDER_OFF,
	O_JIG_GRIP_CYLINDER_ON_OFF,
	O_JIG_GRIP_CYLINDER_ON,
	O_JIG_GRIP_CYLINDER_OFF,
	O_JIG_TRAY_STATE,
	O_JIG_STACKER_SIGNAL,
	O_JIG_ROLL_CYLINDER_ON_OFF,
	O_JIG_CHANGE_X,
	O_JIG_CHANGE_Y,
	O_JIG_CHANGE_Z,
	O_JIG_CHANGE_LOCK,

	O_CABLE_CHECK_CH,
	O_CABLE_CHECK_SR,
	O_CABLE_CHECK_UPPER,
	O_CABLE_CHECK_LOWER,

	O_MOTOR,
	O_MOTOR_RUN,
	O_MOTOR_STOP,
	O_MOTOR_RESET,
	O_MOTOR_HOME,
	O_MOTOR_STEP,

	O_REMOTE_CONTROL,
	O_CHAMBER_STOP,

	O_CH_RUN_STATE, //kjhw_130702

	O_BMS_KEY_ON, //kjg_101124
	O_BMS_CHARGE_ON,
	O_BMS_RELAY_ON,

	O_MARS_LIGHT,	//jhkw_130711

	O_OUT_CONCENT1, //jhkw_130319s
	O_OUT_CONCENT2,
	O_OUT_CONCENT3,
	O_OUT_CONCENT4,  //jhkw_130319e
	O_OUT_CONCENT5,	//jhkw_161113
	O_OUT_CONCENT6,	//jhkw_161113
	O_OUT_CONCENT7,	//jhkw_180206
	O_OUT_CONCENT8,	//jhkw_180206

	O_OUT_DC_FAN,	//jhkw_130924	
	O_OUT_PARALLEL_MODE, //jhkw_130924

	O_MUX_A_P, //kjhw_151021s
	O_MUX_A_N,
	O_MUX_B_P,
	O_MUX_B_N, //kjhw_151021e

	O_TEST_01,		//kjhw_150401
	O_TEST_02,		//kjhw_150401
	O_TEST_03,		//kjhw_150401
	O_TEST_04		//kjhw_150401
} out_function_no;

/*kjg_w for C_ENERLAND_5V_250A
//internal out signal
#define I_OUT_RUN_LED_2				10

//module io max define
#define MAX_M_IN_BYTE				2
//#define MAX_M_IN_BYTE				3 //for C_ENERLAND_5V_250A
#define MAX_M_OUT_BYTE				2
#define MAX_M_IN_SIGNAL				(MAX_M_IN_BYTE * BITS_PER_BYTE)
#define MAX_M_OUT_SIGNAL			(MAX_M_OUT_BYTE * BITS_PER_BYTE)

//for C_ENERLAND_5V_250A
//module io in signal
#define M_IN_PS_FAIL_7V_1			0
#define M_IN_PS_FAIL_7V_2			1
#define M_IN_PS_FAIL_7V_3			2
#define M_IN_OT_FAIL_1				8
#define M_IN_OT_FAIL_2				9
#define M_IN_OT_FAIL_3				10
#define M_IN_PS_FAIL_3P3V_1			16
#define M_IN_PS_FAIL_3P3V_2			17
#define M_IN_PS_FAIL_3P3V_3			18

//module io out signal
#define M_OUT_PS1					0
#define M_OUT_PS2					1
#define M_OUT_PS3					2
#define M_OUT_PS4					3
#define M_OUT_PS5					4
#define M_OUT_PS6					5
#define M_OUT_PS7					6
#define M_OUT_PS8					7
#define M_OUT_FAN1					12
#define M_OUT_FAN2					13*/

//for C_ENERLAND_5V_250A
//digital io out signal
#define D_OUT_I_RANGE1_3			0
#define D_OUT_PARALLEL_3			3

//digital io in signal
#define D_IN_RIPPLE_SWITCH			6 //for LGC_500V_20A

//digital io out signal
#define D_OUT_RIPPLE_ON_RELAY		6 //for LGC_500V_20A

//watchdog timer address
#define WDT_ADDR_READ					I_ADDR_IN_1
#define WDT_ADDR_WRITE					I_ADDR_OUT_1

//watchdog timer bits
#define WDT_BIT_ERROR					0xFE
#define WDT_BIT_UNREADY					0x00
#define WDT_BIT_READY					0x01
#define WDT_BIT_TEST					0x02
#define WDT_BIT_CLEAR					0x01

//sbc watchdog timer(hs_6637)
#define WDT_ADDR_ENABLE_HS_6637			0x443
#define WDT_ADDR_REFRESH_HS_6637		0x443
#define WDT_ADDR_DISABLE_HS_6637		0x045

//sbc watchdog timer(web_6580)
#define WDT_ADDR_ENABLE_WEB_6580		0x543
#define WDT_ADDR_REFRESH_WEB_6580		0x543
#define WDT_ADDR_DISABLE_WEB_6580		0x543

//sbc watchdog timer(hs_4020)
#define WDT_ADDR_ENABLE_HS_4020			0x500
#define WDT_ADDR_REFRESH_HS_4020		0x500
#define WDT_ADDR_DISABLE_HS_4020		0x500

//sbc watchdog timer(wafer_e669)
#define WDT_ADDR_ENABLE_WAFER_E669		0x443
#define WDT_ADDR_REFRESH_WAFER_E669		0x443
#define WDT_ADDR_DISABLE_WAFER_E669		0x043

//sbc watchdog timer(wafer_lx800)
#define WDT_ADDR_ENABLE_WAFER_LX800		0x6F02
#define WDT_ADDR_REFRESH_WAFER_LX800	0x6F02
#define WDT_ADDR_DISABLE_WAFER_LX800	0x6F02

//sbc watchdog timer(wafer_mark)
#define WDT_ADDR_ENABLE_WAFER_MARK		0x443
#define WDT_ADDR_REFRESH_WAFER_MARK		0x443
#define WDT_ADDR_DISABLE_WAFER_MARK		0x043

#endif
