#ifndef __MODULECONTROL_DEF_H__
#define __MODULECONTROL_DEF_H__

#include "HW_Addr_Cycler_Pack1.h"
//#include "HW_Addr_Cycler_General1.h"
//#include "HW_Addr_Formation_General1.h"

//test condition define
//#define MAX_TEST_STEP         				210
#define MAX_TEST_STEP         				400
#define MAX_PATTERN_DATA					50001	//old
#define MAX_SOC_TRACKING_DATA				20 //20181219 KHK
#define MAX_SQ_ROW_DATA						20 //jhkw_221205 //shhw_230525  15 -> 20
#define MAX_SQ_COL_DATA						20 //jhkw_221205 //shhw_230525 	10 -> 20
//#define MAX_PATTERN_DATA					100001 //100D~
#define MAX_CAN_FUNCTION					10
#define MAX_AUX_FUNCTION					10
#define MAX_COM_TEST_OBJECT					500 //kjg_170810 200->500
#define MAX_LOC_TEST_OBJECT					600 //kjg_170810 500->600
#define MAX_TEST_GRADE        				10
#define MAX_COM_CODE						100
#define MAX_LOC_CODE						700
#define MAX_AUX_CODE						100
#define MAX_CAN_CODE						100
#define MAX_EOL_DATA						200
#define MAX_USERMAP_ROW_DATA				22 //kjhw_140828
#define MAX_USERMAP_COL_DATA				22 //kjhw_140828

//step type
#define STEP_IDLE							0
#define	STEP_CHARGE							1
#define	STEP_DISCHARGE						2
#define	STEP_REST							3
#define	STEP_OCV							4
#define STEP_Z								5
#define	STEP_END							6
#define STEP_CYCLE							7
#define STEP_LOOP							8
#define STEP_PATTERN						9
#define STEP_LONG_TIME_REST					10
#define STEP_EXTERNAL_CAN					11
#define STEP_USERMAP						12 //kjhw_140828
#define STEP_EXTERNAL_CAN_2					13 //kjg_140916

//cali type
#define CALI_IDLE							0
#define CALI_CHARGE							1
#define CALI_DISCHARGE						2

//sum type
#define SUM_ALL								0
#define SUM_CHARGE							1
#define SUM_DISCHARGE						2

//step mode
#define MODE_IDLE							0
#define	MODE_CC_CV							1
#define	MODE_CC								2
#define	MODE_CV								3
#define MODE_DC								4
#define MODE_AC								5
#define MODE_CP								6
#define MODE_CCP							7
#define MODE_CR								8
#define MODE_CP_CC							9
#define MODE_CC_CP							10	//kjh_160623 only bms
#define MODE_USER							11	//20181219 KHK

//value_rate item
#define VALUE_RATE_ITEM_IDLE				0
#define VALUE_RATE_ITEM_AMPARE_HOUR			1
#define VALUE_RATE_ITEM_WATT_HOUR			2

//grade item
#define GRADE_ITEN_IDLE						0
#define GRADE_ITEM_V						1
#define GRADE_ITEM_AMPARE_HOUR				2
#define GRADE_ITEM_Z						3
#define GRADE_ITEM_CAPACITANCE				4

//capacity type
#define CAPACITY_AMPARE_HOURS				0
#define CAPACITY_CAPACITANCE				1

//range define
#define RANGE0								0 //range off
#define RANGE1								1
#define RANGE2								2
#define RANGE3								3
#define RANGE4								4

//operation type
#define OP_INDEPENDENT						0
#define OP_PARALLEL							1

//waveform type
#define WAVEFORM_RECTANGLE					0
#define WAVEFORM_TRIANGLE					1

//safety resistor
#define SR_OPEN								0
#define SR_CLOSE							1

//mux_scan
#define MAX_SLOT							1024
#define SCAN_DIV_1							5000

//save flag
#define SAVE_FLAG_MONITORING_DATA			0
#define SAVE_FLAG_SAVING_END				1
#define SAVE_FLAG_SAVING_TIME				2
#define SAVE_FLAG_SAVING_DELTA_V			3
#define SAVE_FLAG_SAVING_DELTA_I			4
#define SAVE_FLAG_SAVING_DELTA_TEMP			5
#define SAVE_FLAG_SAVING_DELTA_P			6
#define SAVE_FLAG_SAVING_ETC				7
#define SAVE_FLAG_RECORD_DATA				8
#define SAVE_FLAG_SAVING_PAUSE				9	//csk_190517

//attribute list
#define ATTR_IDLE							0
#define ATTR_CHECK1_START					1	//1step charge
#define ATTR_CHECK1_1						2
#define ATTR_CHECK1_2						3
#define ATTR_CHECK1_3						4
#define ATTR_CHECK1_4						5
#define ATTR_CHECK1_5						6
#define ATTR_CHECK1_6						7
#define ATTR_CHECK1_7						8
#define ATTR_CHECK1_8						9
#define ATTR_CHECK1_9						10
#define ATTR_CHECK1_10						11
#define ATTR_CHECK1_END						12
#define ATTR_DC1_START						21	//1step discharge
#define ATTR_DC1_1							22
#define ATTR_DC1_2							23
#define ATTR_DC1_3							24
#define ATTR_DC1_4							25
#define ATTR_DC1_5							26
#define ATTR_DC1_6							27
#define ATTR_DC1_7							28
#define ATTR_DC1_8							29
#define ATTR_DC1_9							30
#define ATTR_DC1_10							31
#define ATTR_DC1_END						32
#define ATTR_DC2_START						41	//discharge -> rest -> discharge
#define ATTR_DC2_1							42
#define ATTR_DC2_2							43
#define ATTR_DC2_3							44
#define ATTR_DC2_4							45
#define ATTR_DC2_5							46
#define ATTR_DC2_6							47
#define ATTR_DC2_7							48
#define ATTR_DC2_8							49
#define ATTR_DC2_9							50
#define ATTR_DC2_10							51
#define ATTR_DC2_END						52
#define ATTR_DC3_START						61	//chargge -> rest -> charge
#define ATTR_DC3_1							62
#define ATTR_DC3_2							63
#define ATTR_DC3_3							64
#define ATTR_DC3_4							65
#define ATTR_DC3_5							66
#define ATTR_DC3_6							67
#define ATTR_DC3_7							68
#define ATTR_DC3_8							69
#define ATTR_DC3_9							70
#define ATTR_DC3_10							71
#define ATTR_DC3_END						72
#define ATTR_SUB_START						81 //multi step charge/discharge
#define ATTR_SUB_1							82
#define ATTR_SUB_2							83
#define ATTR_SUB_3							84
#define ATTR_SUB_4							85
#define ATTR_SUB_5							86
#define ATTR_SUB_6							87
#define ATTR_SUB_7							88
#define ATTR_SUB_8							89
#define ATTR_SUB_9							90
#define ATTR_SUB_10							91
#define ATTR_SUB_END						92
#define ATTR_TOTAL_CHECK					100 //total check
#define ATTR_CHECK2_START					101 //for formation 1step charge
#define ATTR_CHECK2_1						102
#define ATTR_CHECK2_2						103
#define ATTR_CHECK2_3						104
#define ATTR_CHECK2_4						105
#define ATTR_CHECK2_5						106
#define ATTR_CHECK2_6						107
#define ATTR_CHECK2_7						108
#define ATTR_CHECK2_8						109
#define ATTR_CHECK2_9						110
#define ATTR_CHECK2_10						111
#define ATTR_CHECK2_END						112
#define ATTR_CHECK3_START					121 //for formation 2step ocv
#define ATTR_CHECK3_1						122
#define ATTR_CHECK3_2						123
#define ATTR_CHECK3_3						124
#define ATTR_CHECK3_4						125
#define ATTR_CHECK3_5						126
#define ATTR_CHECK3_6						127
#define ATTR_CHECK3_7						128
#define ATTR_CHECK3_8						129
#define ATTR_CHECK3_9						130
#define ATTR_CHECK3_10						131
#define ATTR_CHECK3_END						132
#define ATTR_CHECK4_START					141 //for triangle_cycler
#define ATTR_CHECK4_1						142
#define ATTR_CHECK4_2						143
#define ATTR_CHECK4_3						144
#define ATTR_CHECK4_4						145
#define ATTR_CHECK4_5						146
#define ATTR_CHECK4_6						147
#define ATTR_CHECK4_7						148
#define ATTR_CHECK4_8						149
#define ATTR_CHECK4_9						150
#define ATTR_CHECK4_10						151
#define ATTR_CHECK4_END						152

//common object index
#define IDX_COM_OBJ_TOTAL_STEP				0 //common test conditon
#define IDX_COM_OBJ_ATTRIBUTE_COUNT			1
#define IDX_COM_OBJ_AUX_CV_UPPER_VALUE		2
#define IDX_COM_OBJ_AUX_CV_LOWER_VALUE		3
#define IDX_COM_OBJ_CAN_CV_UPPER_VALUE		4
#define IDX_COM_OBJ_CAN_CV_LOWER_VALUE		5
#define IDX_COM_OBJ_TOTAL_PATTERN			7
#define IDX_COM_OBJ_FAULT_HW_UPPER_V		10 //hard fault condition
#define IDX_COM_OBJ_FAULT_HW_LOWER_V		11
#define IDX_COM_OBJ_FAULT_HW_UPPER_I		12
#define IDX_COM_OBJ_FAULT_HW_LOWER_I		13
#define IDX_COM_OBJ_FAULT_HW_UPPER_TEMP		14
#define IDX_COM_OBJ_FAULT_HW_LOWER_TEMP		15
#define IDX_COM_OBJ_FAULT_UPPER_V			20 //soft fault condition
#define IDX_COM_OBJ_FAULT_LOWER_V			21
#define IDX_COM_OBJ_FAULT_UPPER_I			22
#define IDX_COM_OBJ_FAULT_LOWER_I			23
#define IDX_COM_OBJ_FAULT_UPPER_AMPARE_HOUR	24
#define IDX_COM_OBJ_FAULT_LOWER_AMPARE_HOUR	25
#define IDX_COM_OBJ_FAULT_UPPER_TEMP		26
#define IDX_COM_OBJ_FAULT_LOWER_TEMP		27
#define IDX_COM_OBJ_FAULT_MAX_CH			28
//#define IDX_COM_OBJ_FAULT_UPPER_CAPACITANCE	29
//#define IDX_COM_OBJ_FAULT_LOWER_CAPACITANCE	30
#define IDX_COM_OBJ_FAULT_UPPER_WATT_HOUR	31
#define IDX_COM_OBJ_FAULT_LOWER_WATT_HOUR	32
#define IDX_COM_OBJ_FAULT_UPPER_P			33
#define IDX_COM_OBJ_FAULT_CHARGE_UPPER_V	40 //for formation common_safety start
#define IDX_COM_OBJ_FAULT_CHARGE_UPPER_AMPARE_HOUR	41
#define IDX_COM_OBJ_FAULT_CHARGE_CHECK_V	42
#define IDX_COM_OBJ_FAULT_CHARGE_CHECK_TIME	43
#define IDX_COM_OBJ_FAULT_CHARGE_END_UPPER_V	44
#define IDX_COM_OBJ_FAULT_CHARGE_LOWER_I	45
#define IDX_COM_OBJ_FAULT_DISCHARGE_LOWER_V	46
#define IDX_COM_OBJ_FAULT_DISCHARGE_RUN_TIME	47
#define IDX_COM_OBJ_FAULT_DISCHARGE_LOWER_AMPARE_HOUR	48
#define IDX_COM_OBJ_FAULT_OVER_CURRENT_LIMIT	49
#define IDX_COM_OBJ_FAULT_COMP_V_T1			50
#define IDX_COM_OBJ_FAULT_COMP_LOWER_V1		51
#define IDX_COM_OBJ_FAULT_COMP_UPPER_V1		52
#define IDX_COM_OBJ_FAULT_COMP_V_T2			53
#define IDX_COM_OBJ_FAULT_COMP_LOWER_V2		54
#define IDX_COM_OBJ_FAULT_COMP_UPPER_V2		55
#define IDX_COM_OBJ_FAULT_COMP_V_T3			56
#define IDX_COM_OBJ_FAULT_COMP_LOWER_V3		57
#define IDX_COM_OBJ_FAULT_COMP_UPPER_V3		58
#define IDX_COM_OBJ_FAULT_COMP_LOWER_CV_TIME	59
#define IDX_COM_OBJ_FAULT_COMP_UPPER_CV_TIME	60
#define IDX_COM_OBJ_FAULT_COMP_I_T1			61
#define IDX_COM_OBJ_FAULT_COMP_LOWER_I1		62
#define IDX_COM_OBJ_FAULT_COMP_UPPER_I1		63 //for formation common_safety end

#define IDX_COM_OBJ_FAULT_DELTA_V			69	//jhkw_160828
#define IDX_COM_OBJ_FAULT_COMP_AUX_V		70	//kjhw_150730
#define IDX_COM_OBJ_AUX_TEMP_P_UPPER_VALUE	71 //jhkw_160123s
#define IDX_COM_OBJ_AUX_TEMP_P_LOWER_VALUE	72
#define IDX_COM_OBJ_AUX_TEMP_C_UPPER_VALUE	73
#define IDX_COM_OBJ_AUX_TEMP_C_LOWER_VALUE	74
#define IDX_COM_OBJ_CAN_TEMP_P_UPPER_VALUE	75
#define IDX_COM_OBJ_CAN_TEMP_P_LOWER_VALUE	76
#define IDX_COM_OBJ_CAN_TEMP_C_UPPER_VALUE	77
#define IDX_COM_OBJ_CAN_TEMP_C_LOWER_VALUE	78 //jhkw_160123e
#define IDX_COM_OBJ_SCHEDULE_LINK_FLAG		79 //20181219 khk
#define IDX_COM_OBJ_USER_DEFINE_MODE_FLAG	80 //20181219 khk
#define IDX_COM_OBJ_RPTSOC					81 //jhkw_190503
#define IDX_COM_OBJ_SOC						82 //jhkw_190503
#define IDX_COM_OBJ_CURRENT_AH				83 //jhkw_191108s
#define IDX_COM_OBJ_INITIAL_AH				84
#define IDX_COM_OBJ_CRATE_FACTOR			85 //jhkw_191108e
#define IDX_COM_OBJ_FAULT_FIX_UPPER_AUXV	86 //jhkw_200507s
#define IDX_COM_OBJ_FAULT_FIX_LOWER_AUXV	87
#define IDX_COM_OBJ_FAULT_FIX_UPPER_TEMP	88 //jhkw_200507e
#define IDX_COM_OBJ_FAULT_FIX_DELTA_I		89 //shhw_230605
#define IDX_COM_OBJ_FAULT_FIX_DELTA_AUXV	90 //shhw_230605

#define IDX_COM_OBJ_CAN_FUNC_DIV_1			200
#define IDX_COM_OBJ_CAN_FUNC_DIV_2			201
#define IDX_COM_OBJ_CAN_FUNC_DIV_3			202
#define IDX_COM_OBJ_CAN_FUNC_DIV_4			203
#define IDX_COM_OBJ_CAN_FUNC_DIV_5			204
#define IDX_COM_OBJ_CAN_FUNC_DIV_6			205
#define IDX_COM_OBJ_CAN_FUNC_DIV_7			206
#define IDX_COM_OBJ_CAN_FUNC_DIV_8			207
#define IDX_COM_OBJ_CAN_FUNC_DIV_9			208
#define IDX_COM_OBJ_CAN_FUNC_DIV_10			209
#define IDX_COM_OBJ_CAN_VALUE_1				210
#define IDX_COM_OBJ_CAN_VALUE_2				211
#define IDX_COM_OBJ_CAN_VALUE_3				212
#define IDX_COM_OBJ_CAN_VALUE_4				213
#define IDX_COM_OBJ_CAN_VALUE_5				214
#define IDX_COM_OBJ_CAN_VALUE_6				215
#define IDX_COM_OBJ_CAN_VALUE_7				216
#define IDX_COM_OBJ_CAN_VALUE_8				217
#define IDX_COM_OBJ_CAN_VALUE_9				218
#define IDX_COM_OBJ_CAN_VALUE_10			219
#define IDX_COM_OBJ_CAN_VALUE_TYPE_1		220
#define IDX_COM_OBJ_CAN_VALUE_TYPE_2		221
#define IDX_COM_OBJ_CAN_VALUE_TYPE_3		222
#define IDX_COM_OBJ_CAN_VALUE_TYPE_4		223
#define IDX_COM_OBJ_CAN_VALUE_TYPE_5		224
#define IDX_COM_OBJ_CAN_VALUE_TYPE_6		225
#define IDX_COM_OBJ_CAN_VALUE_TYPE_7		226
#define IDX_COM_OBJ_CAN_VALUE_TYPE_8		227
#define IDX_COM_OBJ_CAN_VALUE_TYPE_9		228
#define IDX_COM_OBJ_CAN_VALUE_TYPE_10		229
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_1		230 //kjg_170810_s
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_2		231
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_3		232
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_4		233
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_5		234
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_6		235
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_7		236
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_8		237
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_9		238
#define IDX_COM_OBJ_CAN_FUNC_DIV_TMP_10		239
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_1		240
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_2		241
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_3		242
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_4		243
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_5		244
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_6		245
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_7		246
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_8		247
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_9		248
#define IDX_COM_OBJ_CAN_COMP_TYPE_TMP_10	249
#define IDX_COM_OBJ_CAN_VALUE_TMP_1			250
#define IDX_COM_OBJ_CAN_VALUE_TMP_2			251
#define IDX_COM_OBJ_CAN_VALUE_TMP_3			252
#define IDX_COM_OBJ_CAN_VALUE_TMP_4			253
#define IDX_COM_OBJ_CAN_VALUE_TMP_5			254
#define IDX_COM_OBJ_CAN_VALUE_TMP_6			255
#define IDX_COM_OBJ_CAN_VALUE_TMP_7			256
#define IDX_COM_OBJ_CAN_VALUE_TMP_8			257
#define IDX_COM_OBJ_CAN_VALUE_TMP_9			258
#define IDX_COM_OBJ_CAN_VALUE_TMP_10		259 //kjg_170810_e

#define IDX_COM_OBJ_AUX_FUNC_DIV_1			300
#define IDX_COM_OBJ_AUX_FUNC_DIV_2			301
#define IDX_COM_OBJ_AUX_FUNC_DIV_3			302
#define IDX_COM_OBJ_AUX_FUNC_DIV_4			303
#define IDX_COM_OBJ_AUX_FUNC_DIV_5			304
#define IDX_COM_OBJ_AUX_FUNC_DIV_6			305
#define IDX_COM_OBJ_AUX_FUNC_DIV_7			306
#define IDX_COM_OBJ_AUX_FUNC_DIV_8			307
#define IDX_COM_OBJ_AUX_FUNC_DIV_9			308
#define IDX_COM_OBJ_AUX_FUNC_DIV_10			309
#define IDX_COM_OBJ_AUX_VALUE_1				310
#define IDX_COM_OBJ_AUX_VALUE_2				311
#define IDX_COM_OBJ_AUX_VALUE_3				312
#define IDX_COM_OBJ_AUX_VALUE_4				313
#define IDX_COM_OBJ_AUX_VALUE_5				314
#define IDX_COM_OBJ_AUX_VALUE_6				315
#define IDX_COM_OBJ_AUX_VALUE_7				316
#define IDX_COM_OBJ_AUX_VALUE_8				317
#define IDX_COM_OBJ_AUX_VALUE_9				318
#define IDX_COM_OBJ_AUX_VALUE_10			319
#define IDX_COM_OBJ_AUX_VALUE_TYPE_1		320
#define IDX_COM_OBJ_AUX_VALUE_TYPE_2		321
#define IDX_COM_OBJ_AUX_VALUE_TYPE_3		322
#define IDX_COM_OBJ_AUX_VALUE_TYPE_4		323
#define IDX_COM_OBJ_AUX_VALUE_TYPE_5		324
#define IDX_COM_OBJ_AUX_VALUE_TYPE_6		325
#define IDX_COM_OBJ_AUX_VALUE_TYPE_7		326
#define IDX_COM_OBJ_AUX_VALUE_TYPE_8		327
#define IDX_COM_OBJ_AUX_VALUE_TYPE_9		328
#define IDX_COM_OBJ_AUX_VALUE_TYPE_10		329
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_1		330 //kjg_170810_s
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_2		331
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_3		332
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_4		333
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_5		334
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_6		335
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_7		336
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_8		337
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_9		338
#define IDX_COM_OBJ_AUX_FUNC_DIV_TMP_10		339
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_1		340
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_2		341
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_3		342
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_4		343
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_5		344
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_6		345
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_7		346
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_8		347
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_9		348
#define IDX_COM_OBJ_AUX_COMP_TYPE_TMP_10	349
#define IDX_COM_OBJ_AUX_VALUE_TMP_1			350
#define IDX_COM_OBJ_AUX_VALUE_TMP_2			351
#define IDX_COM_OBJ_AUX_VALUE_TMP_3			352
#define IDX_COM_OBJ_AUX_VALUE_TMP_4			353
#define IDX_COM_OBJ_AUX_VALUE_TMP_5			354
#define IDX_COM_OBJ_AUX_VALUE_TMP_6			355
#define IDX_COM_OBJ_AUX_VALUE_TMP_7			356
#define IDX_COM_OBJ_AUX_VALUE_TMP_8			357
#define IDX_COM_OBJ_AUX_VALUE_TMP_9			358
#define IDX_COM_OBJ_AUX_VALUE_TMP_10		359 //kjg_170810_e

//local object index
#define IDX_LOC_OBJ_CLIENT_STEP_NO			0 //step condition
#define IDX_LOC_OBJ_STEP_NO					1
#define IDX_LOC_OBJ_TYPE					2
#define IDX_LOC_OBJ_MODE					3
#define IDX_LOC_OBJ_ATTRIBUTE				4
#define IDX_LOC_OBJ_REF_V					5
#define IDX_LOC_OBJ_REF_I					6
#define IDX_LOC_OBJ_REF_P					7
#define IDX_LOC_OBJ_RANGE_V					8
#define IDX_LOC_OBJ_RANGE_I					9
#define IDX_LOC_OBJ_TEST_END				10
#define IDX_LOC_OBJ_TOTAL_SUB_STEP			11
#define IDX_LOC_OBJ_CAPACITANCE_V1			12
#define IDX_LOC_OBJ_CAPACITANCE_V2			13
#define IDX_LOC_OBJ_Z_T1					14
#define IDX_LOC_OBJ_Z_T2					15
#define IDX_LOC_OBJ_LC_T1					16
#define IDX_LOC_OBJ_LC_T2					17
#define IDX_LOC_OBJ_REF_R					18
#define IDX_LOC_OBJ_PATTERN_INDEX			19
#define IDX_LOC_OBJ_REF_V2					20 //for discharge cv ref at pattern
#define IDX_LOC_OBJ_CYCLE_PAUSE				21
#define IDX_LOC_OBJ_RANGE_V2				22
#define IDX_LOC_OBJ_PATTERN_FILE_SIZE		23
#define IDX_LOC_OBJ_PATTERN_FILE_CHECKSUM	24
#define IDX_LOC_OBJ_REF_I2					25 //cv_pattern kjhw_150210
#define IDX_LOC_OBJ_TIMESCH_STEP_NO			26 //timeschedule kjh_160418
#define IDX_LOC_OBJ_TIMESCH_INIT			27 //timeschedule kjh_160418
#define IDX_LOC_OBJ_CHAMBER_STEP_CHECK_FLAG		28 //flag check kjhw_150821
#define IDX_LOC_OBJ_CAN_COMM_STEP_CHECK_FLAG	29 //flag check kjhw_150821
#define IDX_LOC_OBJ_PATTERN_UPDATED			30 //kjg_170810
#define IDX_LOC_OBJ_USERMAP_UPDATED			31 //kjg_170810

//20181219 KHK-------------------------------
#define IDX_LOC_OBJ_SOC_TRACKING_INDEX		32
#define IDX_LOC_OBJ_SOC_TRACKING_FLAG		33 
#define IDX_LOC_OBJ_CELL_BALANCING_FLAG		34 
#define IDX_LOC_OBJ_LIMIT_CURRENT_LOWER		35 
#define IDX_LOC_OBJ_CELL_BALANCING_START	36 
#define IDX_LOC_OBJ_CELL_BALANCING_STOP		37 
#define IDX_LOC_OBJ_CELL_BALANCING_END		38 
#define IDX_LOC_OBJ_USER_DEFINE_MODE_FLAG	39
//--------------------------------------------

#define IDX_LOC_OBJ_SAVE_DELTA_T			40 //save condition
#define IDX_LOC_OBJ_SAVE_DELTA_V			41
#define IDX_LOC_OBJ_SAVE_DELTA_I			42
#define IDX_LOC_OBJ_SAVE_DELTA_TEMP			43
#define IDX_LOC_OBJ_SAVE_DELTA_P			44
#define IDX_LOC_OBJ_SAVE_RECORD_T1			45
#define IDX_LOC_OBJ_SAVE_RECORD_T2			46
#define IDX_LOC_OBJ_SAVE_RECORD_T3			47
#define IDX_LOC_OBJ_SAVE_RECORD_T4			48
#define IDX_LOC_OBJ_SAVE_RECORD_T5			49
#define IDX_LOC_OBJ_RECODE_DELTA_TIME		50
#define IDX_LOC_OBJ_LIMIT_CURRENT_UPPER		51	//jhkw_190325 
#define IDX_LOC_OBJ_LIMIT_CURRENT_UPPER_FLAG	52	//jhkw_200524
#define IDX_LOC_OBJ_DISCHARGE_SOC_TRACKING_FLAG	53	//jhkw_201102
#define IDX_LOC_OBJ_SEQUENCE_CHARGE_FLAG		54	//jhkw_221205

#define IDX_LOC_OBJ_END_CONDITION_START		60 //end condition start
#define IDX_LOC_OBJ_END_SUM_AMPARE_HOUR		60
#define IDX_LOC_OBJ_END_SUM_AMPARE_HOUR_TYPE	61//0:all, 1:charge, 2:discharge
#define IDX_LOC_OBJ_END_SUM_AMPARE_HOUR_BRANCH	62
#define IDX_LOC_OBJ_END_SUM_WATT_HOUR		63
#define IDX_LOC_OBJ_END_SUM_WATT_HOUR_TYPE	64	//0:all, 1:charge, 2:discharge
#define IDX_LOC_OBJ_END_SUM_WATT_HOUR_BRANCH	65
#define IDX_LOC_OBJ_END_SUM_TIME_DAY		66
#define IDX_LOC_OBJ_END_SUM_TIME			67
#define IDX_LOC_OBJ_END_SUM_TIME_BRANCH		68

#define IDX_LOC_OBJ_END_V_UPPER				69
#define IDX_LOC_OBJ_END_V_UPPER_BRANCH		70
#define IDX_LOC_OBJ_END_V_LOWER				71
#define IDX_LOC_OBJ_END_V_LOWER_BRANCH		72
#define IDX_LOC_OBJ_END_TIME_DAY			73
#define IDX_LOC_OBJ_END_TIME				74
#define IDX_LOC_OBJ_END_TIME_BRANCH			75
#define IDX_LOC_OBJ_END_CV_TIME_DAY			76
#define IDX_LOC_OBJ_END_CV_TIME				77
#define IDX_LOC_OBJ_END_CV_TIME_BRANCH		78
#define IDX_LOC_OBJ_END_CC_TIME_DAY			79
#define IDX_LOC_OBJ_END_CC_TIME				80
#define IDX_LOC_OBJ_END_CC_TIME_BRANCH		81
#define IDX_LOC_OBJ_END_AMPARE_HOUR			82
#define IDX_LOC_OBJ_END_AMPARE_HOUR_BRANCH	83
#define IDX_LOC_OBJ_END_WATT_HOUR			84
#define IDX_LOC_OBJ_END_WATT_HOUR_BRANCH	85
#define IDX_LOC_OBJ_END_AMPARE_HOUR_RATE	86
#define IDX_LOC_OBJ_END_AMPARE_HOUR_RATE_BRANCH	87
#define IDX_LOC_OBJ_END_AMPARE_HOUR_RATE_COMPARE	88
#define IDX_LOC_OBJ_END_WATT_HOUR_RATE		89
#define IDX_LOC_OBJ_END_WATT_HOUR_RATE_BRANCH	90
#define IDX_LOC_OBJ_END_WATT_HOUR_RATE_COMPARE	91

#define IDX_LOC_OBJ_END_CYCLE_COUNT			92
#define IDX_LOC_OBJ_END_CYCLE_COUNT_BRANCH	93
#define IDX_LOC_OBJ_END_MULTI_CYCLE_COUNT	94
#define IDX_LOC_OBJ_END_MULTI_CYCLE_COUNT_BRANCH	95
#define IDX_LOC_OBJ_END_MULTI_CYCLE_COUNT_COMPARE	96
#define IDX_LOC_OBJ_END_ACC_CYCLE_COUNT		97
#define IDX_LOC_OBJ_END_ACC_CYCLE_COUNT_BRANCH	98
#define IDX_LOC_OBJ_END_ACC_CYCLE_COUNT_COMPARE	99

#define IDX_LOC_OBJ_END_I					100
#define IDX_LOC_OBJ_END_P					101
#define IDX_LOC_OBJ_END_DELTA_V				102
#define IDX_LOC_OBJ_END_DELTA_I				103

#define IDX_LOC_OBJ_END_TIMESCH_DAY			104 //timeschedule kjh_160418
#define IDX_LOC_OBJ_END_TIMESCH_TIME		105 //timeschedule kjh_160418

#define IDX_LOC_OBJ_END_CAN_V_UPPER			120 //kjg_090304 0x1008
#define IDX_LOC_OBJ_END_CAN_V_UPPER_BRANCH	121
#define IDX_LOC_OBJ_END_CAN_V_LOWER			122
#define IDX_LOC_OBJ_END_CAN_V_LOWER_BRANCH	123
#define IDX_LOC_OBJ_END_CAN_TEMP_UPPER		124
#define IDX_LOC_OBJ_END_CAN_TEMP_UPPER_BRANCH	125
#define IDX_LOC_OBJ_END_CAN_TEMP_LOWER		126
#define IDX_LOC_OBJ_END_CAN_TEMP_LOWER_BRANCH	127
#define IDX_LOC_OBJ_END_CAN_SOC_UPPER		128
#define IDX_LOC_OBJ_END_CAN_SOC_UPPER_BRANCH	129
#define IDX_LOC_OBJ_END_CAN_SOC_LOWER		130
#define IDX_LOC_OBJ_END_CAN_SOC_LOWER_BRANCH	131
#define IDX_LOC_OBJ_END_CAN_FAULT			132
#define IDX_LOC_OBJ_END_CAN_FAULT_BRANCH	133

#define IDX_LOC_OBJ_END_AUX_V_UPPER			140
#define IDX_LOC_OBJ_END_AUX_V_UPPER_BRANCH	141
#define IDX_LOC_OBJ_END_AUX_V_LOWER			142
#define IDX_LOC_OBJ_END_AUX_V_LOWER_BRANCH	143
#define IDX_LOC_OBJ_END_AUX_TEMP_UPPER		144
#define IDX_LOC_OBJ_END_AUX_TEMP_UPPER_BRANCH	145
#define IDX_LOC_OBJ_END_AUX_TEMP_LOWER		146
#define IDX_LOC_OBJ_END_AUX_TEMP_LOWER_BRANCH	147
#define IDX_LOC_OBJ_END_SOC					148 //20181219 KHK
#define IDX_LOC_OBJ_END_SOC_BRANCH			149 //20181219 KHK
#define IDX_LOC_OBJ_END_RPT_SOC				150 //20181219 KHK
#define IDX_LOC_OBJ_END_CONDITION_END		159 //end condition end 

#define IDX_LOC_OBJ_FAULT_HW_UPPER_V		160 //hard fault condition
#define IDX_LOC_OBJ_FAULT_HW_LOWER_V		161
#define IDX_LOC_OBJ_FAULT_HW_UPPER_I		162
#define IDX_LOC_OBJ_FAULT_HW_LOWER_I		163
#define IDX_LOC_OBJ_FAULT_HW_UPPER_TEMP		164
#define IDX_LOC_OBJ_FAULT_HW_LOWER_TEMP		165

#define IDX_LOC_OBJ_FAULT_UPPER_OCV			170 //soft fault condition
#define IDX_LOC_OBJ_FAULT_LOWER_OCV			171
#define IDX_LOC_OBJ_FAULT_UPPER_V			172
#define IDX_LOC_OBJ_FAULT_LOWER_V			173
#define IDX_LOC_OBJ_FAULT_UPPER_I			174
#define IDX_LOC_OBJ_FAULT_LOWER_I			175
#define IDX_LOC_OBJ_FAULT_UPPER_AMPARE_HOUR	176
#define IDX_LOC_OBJ_FAULT_LOWER_AMPARE_HOUR	177
#define IDX_LOC_OBJ_FAULT_UPPER_WATT_HOUR	178
#define IDX_LOC_OBJ_FAULT_LOWER_WATT_HOUR	179
#define IDX_LOC_OBJ_FAULT_UPPER_Z			180
#define IDX_LOC_OBJ_FAULT_LOWER_Z			181

#define IDX_LOC_OBJ_FAULT_COMP_V_T1			182
#define IDX_LOC_OBJ_FAULT_COMP_V_T2			183
#define IDX_LOC_OBJ_FAULT_COMP_V_T3			184
#define IDX_LOC_OBJ_FAULT_COMP_LOWER_V1		185
#define IDX_LOC_OBJ_FAULT_COMP_LOWER_V2		186
#define IDX_LOC_OBJ_FAULT_COMP_LOWER_V3		187
#define IDX_LOC_OBJ_FAULT_COMP_UPPER_V1		188
#define IDX_LOC_OBJ_FAULT_COMP_UPPER_V2		189
#define IDX_LOC_OBJ_FAULT_COMP_UPPER_V3		190
#define IDX_LOC_OBJ_FAULT_COMP_I_T1			191
#define IDX_LOC_OBJ_FAULT_COMP_I_T2			192
#define IDX_LOC_OBJ_FAULT_COMP_I_T3			193
#define IDX_LOC_OBJ_FAULT_COMP_LOWER_I1		194
#define IDX_LOC_OBJ_FAULT_COMP_LOWER_I2		195
#define IDX_LOC_OBJ_FAULT_COMP_LOWER_I3		196
#define IDX_LOC_OBJ_FAULT_COMP_UPPER_I1		197
#define IDX_LOC_OBJ_FAULT_COMP_UPPER_I2		198
#define IDX_LOC_OBJ_FAULT_COMP_UPPER_I3		199

#define IDX_LOC_OBJ_FAULT_UPPER_DELTA_V_T	200
#define IDX_LOC_OBJ_FAULT_UPPER_DELTA_V		201
#define IDX_LOC_OBJ_FAULT_LOWER_DELTA_V_T	202
#define IDX_LOC_OBJ_FAULT_LOWER_DELTA_V		203
#define IDX_LOC_OBJ_FAULT_UPPER_DELTA_I_T	204
#define IDX_LOC_OBJ_FAULT_UPPER_DELTA_I		205
#define IDX_LOC_OBJ_FAULT_LOWER_DELTA_I_T	206
#define IDX_LOC_OBJ_FAULT_LOWER_DELTA_I		207
#define IDX_LOC_OBJ_FAULT_UPPER_TEMP		208
#define IDX_LOC_OBJ_FAULT_LOWER_TEMP		209
#define IDX_LOC_OBJ_FAULT_DELTA_TEMP		210
#define IDX_LOC_OBJ_FAULT_UPPER_CAPACITANCE	211
#define IDX_LOC_OBJ_FAULT_LOWER_CAPACITANCE	212
#define IDX_LOC_OBJ_FAULT_CAN_CHECK_FLAG	213 //kjhw_141208
#define IDX_LOC_OBJ_FAULT_CAN_TX_STOP		214 //kjhw_141212
/*#define IDX_LOC_OBJ_FAULT_COND_LOW_DELTA_V	215 //jhkw_180823s
#define IDX_LOC_OBJ_FAULT_COND_UP_DELTA_V	216
#define IDX_LOC_OBJ_FAULT_COND_LOW_DELTA_I	217
#define IDX_LOC_OBJ_FAULT_COND_UP_DELTA_I	218	*///jhkw_180823e
/*kjg_w #define IDX_LOC_OBJ_FAULT_ACC_CYCLE			153
#define IDX_LOC_OBJ_FAULT_ACC_CYCLE_ID		154
#define IDX_LOC_OBJ_FAULT_MULTI_CYCLE		155
#define IDX_LOC_OBJ_FAULT_MULTI_CYCLE_ID	156*/

//contact check
#define IDX_LOC_OBJ_FAULT_CHECK_UPPER_V		220
#define IDX_LOC_OBJ_FAULT_CHECK_LOWER_V		221
#define IDX_LOC_OBJ_FAULT_CHECK_UPPER_I		222
#define IDX_LOC_OBJ_FAULT_CHECK_LOWER_I		223
#define IDX_LOC_OBJ_FAULT_CHECK_CONTACT_BAD1	224
#define IDX_LOC_OBJ_FAULT_CHECK_CONTACT_BAD2	225
#define IDX_LOC_OBJ_FAULT_CHECK_CONTACT_BAD3	226

//formation contact check
#define IDX_LOC_OBJ_FAULT_CHECK_DETECT_V	227
#define IDX_LOC_OBJ_FAULT_CHECK_REVERSE_V	228
#define IDX_LOC_OBJ_FAULT_CHECK_UPPER_OCV	229
#define IDX_LOC_OBJ_FAULT_CHECK_LOWER_OCV	230
#define IDX_LOC_OBJ_FAULT_CHECK_I_JUDGE_RATIO	231
#define IDX_LOC_OBJ_FAULT_CHECK_UPPER_DELTA_V	232
#define IDX_LOC_OBJ_FAULT_CHECK_LOWER_DELTA_V	233

//formation step ng condition
#define IDX_LOC_OBJ_FAULT_VOLTAGE_DATA_MIN	234
#define IDX_LOC_OBJ_FAULT_VOLTAGE_DATA_MAX	235
#define IDX_LOC_OBJ_FAULT_VOLTAGE_AVG_MIN	236
#define IDX_LOC_OBJ_FAULT_VOLTAGE_AVG_MAX	237
#define IDX_LOC_OBJ_FAULT_AMPARE_HOUR_DATA_MIN	238
#define IDX_LOC_OBJ_FAULT_AMPARE_HOUR_DATA_MAX	239
#define IDX_LOC_OBJ_FAULT_AMPARE_HOUR_AVG_MIN	240
#define IDX_LOC_OBJ_FAULT_AMPARE_HOUR_AVG_MAX	241
#define IDX_LOC_OBJ_FAULT_POWER_DATA_MIN	242
#define IDX_LOC_OBJ_FAULT_POWER_DATA_MAX	243
#define IDX_LOC_OBJ_FAULT_POWER_AVG_MIN		244
#define IDX_LOC_OBJ_FAULT_POWER_AVG_MAX		245

#define IDX_LOC_OBJ_CAN_FUNC_DIV_1			300
#define IDX_LOC_OBJ_CAN_FUNC_DIV_2			301
#define IDX_LOC_OBJ_CAN_FUNC_DIV_3			302
#define IDX_LOC_OBJ_CAN_FUNC_DIV_4			303
#define IDX_LOC_OBJ_CAN_FUNC_DIV_5			304
#define IDX_LOC_OBJ_CAN_FUNC_DIV_6			305
#define IDX_LOC_OBJ_CAN_FUNC_DIV_7			306
#define IDX_LOC_OBJ_CAN_FUNC_DIV_8			307
#define IDX_LOC_OBJ_CAN_FUNC_DIV_9			308
#define IDX_LOC_OBJ_CAN_FUNC_DIV_10			309
#define IDX_LOC_OBJ_CAN_VALUE_1				310
#define IDX_LOC_OBJ_CAN_VALUE_2				311
#define IDX_LOC_OBJ_CAN_VALUE_3				312
#define IDX_LOC_OBJ_CAN_VALUE_4				313
#define IDX_LOC_OBJ_CAN_VALUE_5				314
#define IDX_LOC_OBJ_CAN_VALUE_6				315
#define IDX_LOC_OBJ_CAN_VALUE_7				316
#define IDX_LOC_OBJ_CAN_VALUE_8				317
#define IDX_LOC_OBJ_CAN_VALUE_9				318
#define IDX_LOC_OBJ_CAN_VALUE_10			319
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_1		320
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_2		321
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_3		322
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_4		323
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_5		324
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_6		325
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_7		326
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_8		327
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_9		328
#define IDX_LOC_OBJ_CAN_VALUE_TYPE_10		329
#define IDX_LOC_OBJ_CAN_BRANCH_1			330
#define IDX_LOC_OBJ_CAN_BRANCH_2			331
#define IDX_LOC_OBJ_CAN_BRANCH_3			332
#define IDX_LOC_OBJ_CAN_BRANCH_4			333
#define IDX_LOC_OBJ_CAN_BRANCH_5			334
#define IDX_LOC_OBJ_CAN_BRANCH_6			335
#define IDX_LOC_OBJ_CAN_BRANCH_7			336
#define IDX_LOC_OBJ_CAN_BRANCH_8			337
#define IDX_LOC_OBJ_CAN_BRANCH_9			338
#define IDX_LOC_OBJ_CAN_BRANCH_10			339
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_1		340 //kjg_170810_s
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_2		341
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_3		342
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_4		343
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_5		344
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_6		345
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_7		346
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_8		347
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_9		348
#define IDX_LOC_OBJ_CAN_FUNC_DIV_TMP_10		349
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_1		350
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_2		351
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_3		352
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_4		353
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_5		354
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_6		355
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_7		356
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_8		357
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_9		358
#define IDX_LOC_OBJ_CAN_COMP_TYPE_TMP_10	359
#define IDX_LOC_OBJ_CAN_VALUE_TMP_1			360
#define IDX_LOC_OBJ_CAN_VALUE_TMP_2			361
#define IDX_LOC_OBJ_CAN_VALUE_TMP_3			362
#define IDX_LOC_OBJ_CAN_VALUE_TMP_4			363
#define IDX_LOC_OBJ_CAN_VALUE_TMP_5			364
#define IDX_LOC_OBJ_CAN_VALUE_TMP_6			365
#define IDX_LOC_OBJ_CAN_VALUE_TMP_7			366
#define IDX_LOC_OBJ_CAN_VALUE_TMP_8			367
#define IDX_LOC_OBJ_CAN_VALUE_TMP_9			368
#define IDX_LOC_OBJ_CAN_VALUE_TMP_10		369
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_1		370
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_2		371
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_3		372
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_4		373
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_5		374
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_6		375
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_7		376
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_8		377
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_9		378
#define IDX_LOC_OBJ_CAN_BRANCH_TMP_10		379 //kjg_170810_e

#define IDX_LOC_OBJ_AUX_FUNC_DIV_1			400
#define IDX_LOC_OBJ_AUX_FUNC_DIV_2			401
#define IDX_LOC_OBJ_AUX_FUNC_DIV_3			402
#define IDX_LOC_OBJ_AUX_FUNC_DIV_4			403
#define IDX_LOC_OBJ_AUX_FUNC_DIV_5			404
#define IDX_LOC_OBJ_AUX_FUNC_DIV_6			405
#define IDX_LOC_OBJ_AUX_FUNC_DIV_7			406
#define IDX_LOC_OBJ_AUX_FUNC_DIV_8			407
#define IDX_LOC_OBJ_AUX_FUNC_DIV_9			408
#define IDX_LOC_OBJ_AUX_FUNC_DIV_10			409
#define IDX_LOC_OBJ_AUX_VALUE_1				410
#define IDX_LOC_OBJ_AUX_VALUE_2				411
#define IDX_LOC_OBJ_AUX_VALUE_3				412
#define IDX_LOC_OBJ_AUX_VALUE_4				413
#define IDX_LOC_OBJ_AUX_VALUE_5				414
#define IDX_LOC_OBJ_AUX_VALUE_6				415
#define IDX_LOC_OBJ_AUX_VALUE_7				416
#define IDX_LOC_OBJ_AUX_VALUE_8				417
#define IDX_LOC_OBJ_AUX_VALUE_9				418
#define IDX_LOC_OBJ_AUX_VALUE_10			419
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_1		420
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_2		421
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_3		422
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_4		423
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_5		424
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_6		425
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_7		426
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_8		427
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_9		428
#define IDX_LOC_OBJ_AUX_VALUE_TYPE_10		429
#define IDX_LOC_OBJ_AUX_BRANCH_1			430
#define IDX_LOC_OBJ_AUX_BRANCH_2			431
#define IDX_LOC_OBJ_AUX_BRANCH_3			432
#define IDX_LOC_OBJ_AUX_BRANCH_4			433
#define IDX_LOC_OBJ_AUX_BRANCH_5			434
#define IDX_LOC_OBJ_AUX_BRANCH_6			435
#define IDX_LOC_OBJ_AUX_BRANCH_7			436
#define IDX_LOC_OBJ_AUX_BRANCH_8			437
#define IDX_LOC_OBJ_AUX_BRANCH_9			438
#define IDX_LOC_OBJ_AUX_BRANCH_10			439
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_1		440 //kjg_170810_s
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_2		441
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_3		442
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_4		443
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_5		444
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_6		445
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_7		446
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_8		447
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_9		448
#define IDX_LOC_OBJ_AUX_FUNC_DIV_TMP_10		449
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_1		450
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_2		451
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_3		452
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_4		453
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_5		454
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_6		455
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_7		456
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_8		457
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_9		458
#define IDX_LOC_OBJ_AUX_COMP_TYPE_TMP_10	459
#define IDX_LOC_OBJ_AUX_VALUE_TMP_1			460
#define IDX_LOC_OBJ_AUX_VALUE_TMP_2			461
#define IDX_LOC_OBJ_AUX_VALUE_TMP_3			462
#define IDX_LOC_OBJ_AUX_VALUE_TMP_4			463
#define IDX_LOC_OBJ_AUX_VALUE_TMP_5			464
#define IDX_LOC_OBJ_AUX_VALUE_TMP_6			465
#define IDX_LOC_OBJ_AUX_VALUE_TMP_7			466
#define IDX_LOC_OBJ_AUX_VALUE_TMP_8			467
#define IDX_LOC_OBJ_AUX_VALUE_TMP_9			468
#define IDX_LOC_OBJ_AUX_VALUE_TMP_10		469
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_1		470
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_2		471
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_3		472
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_4		473
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_5		474
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_6		475
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_7		476
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_8		477
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_9		478
#define IDX_LOC_OBJ_AUX_BRANCH_TMP_10		479 //kjg_170810_e
#define IDX_LOC_OBJ_AUX_DELAY_TIME_1		480 //kjhw_170904s
#define IDX_LOC_OBJ_AUX_DELAY_TIME_2		481
#define IDX_LOC_OBJ_AUX_DELAY_TIME_3		482
#define IDX_LOC_OBJ_AUX_DELAY_TIME_4		483
#define IDX_LOC_OBJ_AUX_DELAY_TIME_5		484
#define IDX_LOC_OBJ_AUX_DELAY_TIME_6		485
#define IDX_LOC_OBJ_AUX_DELAY_TIME_7		486
#define IDX_LOC_OBJ_AUX_DELAY_TIME_8		487
#define IDX_LOC_OBJ_AUX_DELAY_TIME_9		488
#define IDX_LOC_OBJ_AUX_DELAY_TIME_10		489 //kjhw_170904e

#define IDX_LOC_OBJ_AUX_CV_UPPER_VALUE		500 //LKI_110222
#define IDX_LOC_OBJ_AUX_CV_LOWER_VALUE		501
#define IDX_LOC_OBJ_CAN_CV_UPPER_VALUE		502
#define IDX_LOC_OBJ_CAN_CV_LOWER_VALUE		503
#define IDX_LOC_OBJ_AUX_TEMP_P_UPPER_VALUE	504 //jhkw_160123s
#define IDX_LOC_OBJ_AUX_TEMP_P_LOWER_VALUE	505
#define IDX_LOC_OBJ_AUX_TEMP_C_UPPER_VALUE	506
#define IDX_LOC_OBJ_AUX_TEMP_C_LOWER_VALUE	507
#define IDX_LOC_OBJ_CAN_TEMP_P_UPPER_VALUE	508
#define IDX_LOC_OBJ_CAN_TEMP_P_LOWER_VALUE	509
#define IDX_LOC_OBJ_CAN_TEMP_C_UPPER_VALUE	510
#define IDX_LOC_OBJ_CAN_TEMP_C_LOWER_VALUE	511 //jhkw_160123e

//module state
#define	M_IDLE								0
#define M_STANDBY							1
#define M_RUN								2
#define M_PAUSE								3
#define M_CALI								4
#define M_FAIL								5

//group state
#define G_IDLE								0
#define G_STANDBY							1
#define G_RUN								2
#define G_PAUSE								3
#define G_CALI								4

//board state
#define B_IDLE								0
#define B_STANDBY							1
#define B_RUN								2
#define B_PAUSE								3
#define B_CALI								4

//channel state
#define	C_IDLE								0
#define	C_STANDBY							1
#define C_RUN								2
#define C_PAUSE								3
#define C_CALI								4
#define C_FAULT								5
#define C_SELF_TEST							6
#define C_PRE_CHARGE						7

//semi switch state
#define SEMI_IDLE							0
#define SEMI_I_P							1
#define SEMI_I_N							2
#define SEMI_I_RANGE1						3
#define SEMI_I_RANGE2						4
#define SEMI_I_RANGE3						5
#define SEMI_I_RANGE4						6
#define SEMI_I_0							3 //kjg_w

//semi switch state //kjg_110813_s
#define SEMI_PRE							1
#define SEMI_V_P							2
#define SEMI_V_N							3

//Group cmd signal - max define 4
#define G_USER_CMD							0
#define G_STEP_CMD							1

//Board cmd signal - max define 4
#define B_USER_CMD							0
#define B_STEP_CMD							1

//Channel cmd signal - max define 4
#define C_USER_CMD							0
#define C_STEP_CMD							1

//CALI CC/CV 20100106
#define CALI_CV								0
#define	CALI_CC								1

//Group user cmd define
#define G_CMD_NONE							0x00
#define G_CMD_RUN							0x01
#define G_CMD_STOP							0x02
#define G_CMD_PAUSE							0x03
#define G_CMD_NET_PAUSE						0x04
#define G_CMD_CONTINUE						0x05
#define G_CMD_NEXT_STEP						0x06
#define G_CMD_RESET							0x07
#define G_CMD_CLEAR							0x08
#define	G_CMD_CHECK							0x09
#define G_CMD_CALI							0X0A

//Board user cmd define
#define B_CMD_NONE							0x00
#define B_CMD_RUN							0x01
#define B_CMD_STOP							0x02
#define B_CMD_PAUSE							0x03
#define B_CMD_NET_PAUSE						0x04
#define B_CMD_CONTINUE						0x05
#define B_CMD_NEXT_STEP						0x06
#define B_CMD_RESET							0x07
#define B_CMD_CLEAR							0x08
#define	B_CMD_CHECK							0x09
#define B_CMD_CALI							0X0A

//Channel user cmd define
#define C_CMD_NONE							0x00
#define C_CMD_RUN							0x01
#define C_CMD_STOP							0x02
#define C_CMD_PAUSE							0x03
#define C_CMD_NET_PAUSE						0x04
#define C_CMD_CONTINUE						0x05
#define C_CMD_NEXT_STEP						0x06
#define C_CMD_RESET							0x07
#define C_CMD_CLEAR							0x08
#define	C_CMD_CHECK							0x09
#define C_CMD_CALI							0X0A

//Board step cmd define
#define B_STEP_CMD_NONE						0x00
#define B_STEP_CMD_RUN						0x01
#define B_STEP_CMD_STOP						0x02
#define B_STEP_CMD_RESET					0x03
#define B_STEP_CMD_CHECK_PAUSE				0x04

//Channel step cmd define
#define C_STEP_CMD_NONE						0x00
#define C_STEP_CMD_RUN						0x01
#define C_STEP_CMD_STOP						0x02
#define C_STEP_CMD_RESET					0x03
#define C_STEP_CMD_CHECK_PAUSE				0x04 //kjg_110813_e

//module signal
#define M_SIG_EXIT_PHASE					0
#define M_SIG_EXIT_TYPE						1
#define M_SIG_EXIT_GROUP					2
#define M_SIG_EXIT_VALUE					3
#define M_SIG_TOWER_LAMP_GROUP				4
#define M_SIG_TOWER_LAMP_CH					5
#define M_SIG_TOWER_LAMP_BUZZER				6
#define M_SIG_TOWER_LAMP_RED				7
#define M_SIG_TOWER_LAMP_AMBER				8
#define M_SIG_TOWER_LAMP_GREEN				9
#define M_SIG_TOWER_LAMP_BLUE				10
#define M_SIG_CABLE_CHECK_PHASE				11
#define M_SIG_CELL_CHECK_PHASE				12
#define M_SIG_BUZZER_SET					13
#define M_SIG_ALARM_SET						14
#define M_SIG_BMS_EOL_PHASE					15
#define M_SIG_BMS_EOL_DELAY1				16
#define M_SIG_BMS_EOL_DELAY2				17
#define M_SIG_BMS_EOL_FLASH_PHASE			18 //kjh_120126
#define M_SIG_BMS_EOL_FLASH_DELAY1			19
#define M_SIG_BMS_EOL_FLASH_DELAY2			20

#define M_SIG_LAMP_RUN						21
#define M_SIG_LAMP_STOP						22
#define M_SIG_CALI_RELAY					23
#define M_SIG_REMOTE_SMPS1					24
#define M_SIG_RUN_LED						25
#define M_SIG_FAN_RELAY						26
#define M_SIG_POWER_OFF						27
#define M_SIG_SMPS_FAULT					28
#define M_SIG_OT_FAULT						29
#define M_SIG_SEND_ERROR_CODE				30
#define M_SIG_TEST_SEND_SAVE_DATA			31
#define M_SIG_CALI_RELAY2					32
#define M_SIG_RUNNING_GROUP					33
#define M_SIG_FAN_ACTIVE					34
#define M_SIG_PACK_ISOLATION_PHASE			35
#define M_SIG_PACK_ISOLATION_COUNT			36
#define M_SIG_BMS_EOL_FLASH_PHASE2			37 //kjg_120126
#define M_SIG_BMS_EOL_FLASH_DELAY3			38
#define M_SIG_BMS_EOL_FLASH_DELAY4			39
#define M_SIG_DAQ_ISOLATION_REPLY_DELAY		40 //kjg_120131
#define M_SIG_PARALLER_MODE					41	//jhkw_131011
#define M_SIG_DAQ_ISOLATION_REPLY_DELAY2	42	//jhkw_150224
#define M_SIG_DAQ_ISOLATION_DIV_CH			43	//jhkw_150224
#define M_SIG_WDT_PHASE						44	//kjg_logic_type_140324

#define M_SIG_CALIBRATION					50
#define M_SIG_CALI_VI_SELECT				51
#define M_SIG_CALI_CD_SELECT				52
#define M_SIG_CALI_BD_START					53
#define M_SIG_CALI_CH						54
#define M_SIG_CALI_STEP						55
#define M_SIG_CALI_GROUP					56
#define M_SIG_CALI_BD_COUNT					57
#define M_SIG_CALI_SEQUENCE					58
#define M_SIG_CALI_BD_RUNNING				59
#define M_SIG_CALI_METER_DIV				60

#define M_SIG_CALI_RANGE_V					61 //kjg_110713_s
#define M_SIG_CALI_RANGE_I					62
#define M_SIG_CALI_CH_FLAG_IDX				63
#define M_SIG_CALI_STEP_TMP					64
#define M_SIG_CALI_VI_SELECT_TMP			65
#define M_SIG_REAL_MEASURE_TYPE				66
#define M_SIG_REAL_MEASURE_GROUP			67
#define M_SIG_REAL_MEASURE_CH				68
#define M_SIG_REAL_MEASURE_PHASE			69
#define M_SIG_REAL_MEASURE_DELAY			70
#define M_SIG_CALI_PARALLEL					71 //kjg_110713_e
#define M_SIG_BMS_EOL3_PHASE				72
#define M_SIG_BMS_EOL3_DELAY1				73
#define M_SIG_BMS_EOL3_DELAY2				74
#define M_SIG_BMS_EOL_CVTN_ID_FLAG			75
#define M_SIG_EOL_PROCEDURE_DIVISION		76 //kjg_120709_s
#define M_SIG_EOL_PROCEDURE_INDEX			77
#define M_SIG_EOL_PROCEDURE_SUB_INDEX		78
#define M_SIG_EOL_PROCEDURE_PHASE			79
#define M_SIG_EOL_PROCEDURE_DATA_INDEX		80

#define M_SIG_EOL_PROCEDURE_DELAY1			81
#define M_SIG_EOL_PROCEDURE_DELAY2			82
#define M_SIG_EOL_PROCEDURE_CHECK_INDEX		83 //kjg_120709_e
#define M_SIG_EOL_PROCEDURE_VBF_FILE_DOWNLOAD	84 //kjg_121004
#define M_SIG_DATA_SAVE_ERROR				85	//jhkw_190830
#define M_SIG_DATA_SAVE_ERROR_PHASE			86	//jhkw_190830

//group signal
#define G_SIG_CMD_RUN						0
#define G_SIG_CMD_STOP						1
#define G_SIG_CMD_PAUSE						2
#define G_SIG_CMD_CONTINUE					3
#define G_SIG_CMD_NEXT_STEP					4
#define G_SIG_CMD_CLEAR						5
#define G_SIG_SAVED_FILE_DELETE_COMPLETE	6
#define G_SIG_DATA_SAVE_COMPLETE			7
#define G_SIG_CONTACT_COMPLETE				8
#define G_SIG_DISCONTACT_COMPLETE			9
#define G_SIG_JIG_FAIL						10
#define G_SIG_NEXT_STEP_EXIST				11
#define G_SIG_EXIT_PHASE					12
#define G_SIG_CMD_RESET						13
#define G_SIG_V_CMD_OUTPUT					14
#define G_SIG_I_CMD_OUTPUT					15
#define G_SIG_NET_CHECK						16
#define G_SIG_LOAD_LINE_CHECK_PHASE			17
#define G_SIG_LOAD_LINE_CHECK_CH			18
#define G_SIG_LOAD_LINE_CHECK_DELAY			19
#define G_SIG_SAFETY_RESISTOR				20
#define G_SIG_DATA_SAVE_FAIL				21
#define G_SIG_ALL_CHANNEL_ERROR				22
#define G_SIG_STEP_ZERO_TIME_RECODE			23
#define G_SIG_DAQ_SAVE						24
#define G_SIG_EXIT_VALUE					25

//board signal
#define B_SIG_CMD_RUN						0
#define B_SIG_CMD_STOP						1
#define B_SIG_CMD_PAUSE						2
#define B_SIG_CMD_CONTINUE					3
#define B_SIG_CMD_NEXT_STEP					4
#define B_SIG_CMD_RESET						5
#define B_SIG_RUN							6
#define B_SIG_STOP							7
#define B_SIG_V_RANGE_SELECT				8
#define B_SIG_I_RANGE_SELECT				9
#define B_SIG_V_CMD_OUTPUT					10
#define B_SIG_I_CMD_OUTPUT					11
#define B_SIG_CHECK_PAUSE					12
#define B_SIG_RESET							13

#define B_SIG_RESET_LATCHED					20
#define B_SIG_HW_FAULT_CLEAR				21

#define B_SIG_OT_DETECT						30 //kjg_110813_s
#define B_SIG_MAIN_SMPS_FAIL				31
#define B_SIG_DAC_I_WARNNING				32
#define B_SIG_CD_SELECT						33 //kjg_110813_e

//channel signal
#define C_SIG_CMD_RUN						0
#define C_SIG_CMD_STOP						1
#define C_SIG_CMD_PAUSE						2
#define C_SIG_CMD_CONTINUE					3
#define C_SIG_CMD_NEXT_STEP					4
#define C_SIG_CMD_RESET						5
#define C_SIG_CMD_CHECK						6
#define C_SIG_CMD_CALI						7
#define C_SIG_CMD_GOTO_STEP					8
#define C_SIG_MODULE_FAULT					9

#define C_SIG_AUX_DAV						10
#define C_SIG_AUX_DAI						11
#define C_SIG_TEST_CONDITION_RCV			12
#define C_SIG_CMD_CHAMBER_CONTINUE			13
#define C_SIG_RESET							14
#define C_SIG_SAVED_FILE_DELETE				15
#define C_SIG_CHECK_DATA_SAVE				16
#define C_SIG_CABLE_CHECK					17
#define C_SIG_BMS_CHECK						18
#define C_SIG_METER_REPLY					19

#define C_SIG_METER_ERROR					20
#define C_SIG_FAULT_HW_OT					21
#define C_SIG_FAULT_M_PS					22
#define C_SIG_V_CMD_OUTPUT					23
#define C_SIG_I_CMD_OUTPUT					24
#define C_SIG_RUN_RELAY_ON					25
#define C_SIG_RUN_RELAY_OFF					26
#define C_SIG_CMD_CYCLE_CONTINUE			27
#define C_SIG_CYCLE_PAUSE_PHASE				28
#define C_SIG_BMS_DEBUG_ON					29

#define C_SIG_CALI_NORMAL					30
#define C_SIG_CALI_CHECK					31
#define C_SIG_CALI_POINT					32
#define C_SIG_CALI_PHASE					33
#define C_SIG_CALI_NORMAL_RESULT_SAVED		34
#define C_SIG_CALI_CHECK_RESULT_SAVED		35
#define C_SIG_CALI_UPDATE					36
#define C_SIG_CALI_UPDATE_PHASE				37
#define C_SIG_EXT_RECEIVE_PARSING_COUNT		38
#define C_SIG_PULSE_COUNT_FLAG				39

#define C_SIG_OUT_SWITCH					40
#define C_SIG_SEMI_SWITCH					41
#define C_SIG_SELECTED_RANGE_I				42
#define C_SIG_C_D_SELECT					43
#define C_SIG_SMPS_FAULT					44
#define C_SIG_FAULT_M_POWER_SWITCH			45
#define C_SIG_FAULT_M_EMG_SWITCH			46
#define C_SIG_FAULT_M_AC_POWER				47
#define C_SIG_FAULT_M_UPS_BATTERY			48
#define C_SIG_USER_CONTROL					49

#define C_SIG_READ_PATTERN_FILE_END			50
#define C_SIG_BMS_ACTIVE					51 //kjg_101124
#define C_SIG_BMS_ACTIVE_PHASE				52
#define C_SIG_BMS_ACTIVE_DELAY				53
#define C_SIG_BMS_KEY_ON_STATE				54
#define C_SIG_BMS_CHARGE_ON_STATE			55
#define C_SIG_BMS_ACTIVE_SIGNAL				56
#define C_SIG_BMS_ACTIVE_START				57
#define C_SIG_RANGE_RELAY_ON				58 //kjg_110814_s
#define C_SIG_RANGE_RELAY_OFF				59

#define C_SIG_GATE_SYNC_CHARGE_ON			60
#define C_SIG_GATE_SYNC_CHARGE_OFF			61
#define C_SIG_GATE_SYNC_DISCHARGE_ON		62
#define C_SIG_GATE_SYNC_DISCHARGE_OFF		63 //kjg_110814_e
#define C_SIG_SSR_ON						64
#define C_SIG_RECV_OUT_SWITCH_1				65 //kjg_120105_s
#define C_SIG_RECV_OUT_SWITCH_2				66
#define C_SIG_OUT_SWITCH_PHASE				67 //kjg_120105_e
#define C_SIG_SEMI_SWITCH_DELAY				68
#define C_SIG_EXT_OP_TYPE					69 //kjg_140916 0:Normal, 1:E_CAN_2

#define C_SIG_EXT_CAN_NM_COUNT_1			70 //kjg_140916_s
#define C_SIG_EXT_CAN_NM_COUNT_2			71
#define C_SIG_EXT_CAN_NM_FLAG_1				72
#define C_SIG_EXT_CAN_NM_FLAG_2				73
#define C_SIG_EXT_CAN_NM_STAT_1				74
#define C_SIG_EXT_CAN_NM_STAT_2				75
#define C_SIG_EXT_CAN_E12_STAT_ERROR		76
#define C_SIG_EXT_CAN_E48_STAT_ERROR		77
#define C_SIG_EXT_CAN_CHM_STAT_ERROR		78
#define C_SIG_EXT_CAN_CHM_NM_STAT			79

#define C_SIG_EXT_CAN_E12_NM_STAT			80
#define C_SIG_EXT_CAN_E48_NM_STAT			81
#define C_SIG_EXT_CAN_CMD_RANGE				82
#define C_SIG_EXT_CAN_FAULT_CLEAR			83 //kjg_140916_e
#define C_SIG_READ_USERMAP_FILE_END			84 //kjhw_140828
#define C_SIG_EXT_CAN_PACK_ISOLATION		85 //kjhw_150216
#define C_SIG_EXT_CAN_CH_ATTRIBUTE			86 //kjhw_150216
#define C_SIG_EXT_CAN_CH_DIV				87 //jhkw_150611
#define C_SIG_OUT_MUX_SELECT				88 //kjhw_151021
#define C_SIG_OUT_MUX_SELECT_PHASE			89 //kjhw_151021

#define C_SIG_TEMP_CONTINUE					90 //jhkw_160123
#define C_SIG_TIMESCH_INIT					91 //kjh_160418
#define C_SIG_TIMESCH_CMD_NEXT_STEP			92 //kjh_160418
#define C_SIG_CMD_TEST_COND_UPDATE			93 //kjg_170810_s
#define C_SIG_CMD_TEST_COND_UPDATE_TYPE		94
#define C_SIG_SOFT_FEEDBACK_DELAY			95
#define C_SIG_SEND_SAVE_MSG_DIVISION		96 //kjg_170810_e
#define C_SIG_READ_END_SOC_TRACKING_FILE	97 //20181219 KHK
#define C_SIG_CELL_BALANCING_STATE			98 //jhkw_190120
#define C_SIG_TX_CELL_BALANCING				99 //jhkw_190120
#define C_SIG_CELL_BALANCING_PHASE			100 //jhkw_190120

#define C_SIG_CMD_CALI_STOP					101 //jhkw_200317
#define C_SIG_READ_END_SEQUENCE_CHARGE_FILE	102 //jhkw_221205

//code
//warnning(message), pause(alarm, ch_pause, message),
//shutdown(alarm, ch_pause, message)
#define M_CD_NONE							0	//quit
#define M_CD_FAULT_AC_POWER_SHORT			1	//pause
#define M_CD_FAULT_AC_POWER_LONG			2	//shutdown
#define M_CD_FAULT_UPS_BATTERY				3	//shutdown
#define M_CD_FAULT_MAIN_EMG_SWITCH			4	//shutdown
#define M_CD_FAULT_SUB_EMG_SWITCH			5	//shutdown
#define M_CD_FAULT_CONTROL_PS				6	//shutdown
#define M_CD_FAULT_OT						7	//shutdown
#define M_CD_FAULT_WARNING_POWER_OFF		8	//warnning
#define M_CD_FAULT_NORMAL_POWER_OFF			9	//shutdown
#define M_CD_FAULT_FORCE_POWER_OFF			10	//force shutdown
#define M_CD_FAULT_NORMAL_TERMINAL_QUIT		11	//quit
#define M_CD_FAULT_FORCE_TERMINAL_QUIT		12	//force quit
#define M_CD_FAULT_NORMAL_TERMINAL_HALT		13	//shutdown
#define M_CD_FAULT_FORCE_TERMINAL_HALT		14	//force shutdown
#define M_CD_FAULT_CPU_WATCHDOG				15	//shutdown
#define M_CD_FAULT_CALI_METER_COMM_ERROR	16	//warnning
#define M_CD_FAULT_CALIBRATOR_COMM_ERROR	17	//warnning
#define M_CD_FAULT_FUSE						18	//shutdown
#define M_CD_FAULT_UPPER_VOLTAGE			19	//shutdown
#define M_CD_FAULT_LOWER_VOLTAGE			20	//shutdown
#define M_CD_FAULT_MAIN_PS					21	//shutdown
#define M_CD_FAULT_CHAMBER					22	//pause
#define M_CD_FAULT_CHAMBER_FIRE				23	//shutdown
#define M_CD_FAULT_FAN						24	//warnning
#define M_CD_FAULT_LOAD_LINE				25	//pause
#define M_CD_FAULT_CHAMBER_DOOR_OPEN		26	//pause
#define M_CD_FAULT_JOB_CHANGE				27	//warnning
#define M_CD_FAULT_PITCH_CHANGE				28	//warnning
#define M_CD_FAULT_CHAMBER_AREA_SENSOR		29	//pause
#define M_CD_FAULT_CHAMBER_MANUAL_DOOR		30	//pause
#define M_CD_FAULT_CHAMBER_AIR				31	//pause
#define M_CD_FAULT_CHAMBER_APR_S			32	//pause
#define M_CD_FAULT_CHAMBER_REF				33	//pause : eocr
#define M_CD_FAULT_CHAMBER_COIL_TRIP		34	//shutdown
#define M_CD_FAULT_CHAMBER_OVER_TEMP		35	//shutdown
#define M_CD_FAULT_CHAMBER_FAN				36	//pause
#define M_CD_FAULT_CHAMBER_SMOKE			37	//shutdown
#define M_CD_FAULT_CHAMBER_POWER			38	//pause
#define M_CD_FAULT_LOAD_LINE2				39	//warnning
#define M_CD_FAULT_POWER_TRANS_OT			40	//shutdown
#define M_CD_FAULT_POWER_REACTOR_OT			41	//shutdown
#define M_CD_FAULT_CAN_WARNNING				42	//warnning
#define M_CD_FAULT_CAN_ERROR				43	//pause or next_step
#define M_CD_FAULT_CHAMBER_REF_ERROR		44	//pause
#define M_CD_FAULT_MCCB						45	//shutdown lki_111010_s
#define M_CD_FAULT_CHAMBER_LEAK				46	//shutdown
#define M_CD_FAULT_CHAMBER_CP_TRIP			47	//pause lki_111010_e
#define M_CD_FAULT_OC						48	//shutdown jhkw_131011
#define M_CD_FAULT_ETC						49	//shutdown jhkw_131011
#define M_CD_FAULT_DC_LINK_FUSE				97	//shutdown	phb_230710

#define G_CD_NONE							0
#define G_CD_FAULT_UPPER_VOLTAGE			50	//pause
#define G_CD_FAULT_UPPER_CURRENT			51	//pause
#define G_CD_FAULT_RUN_TIME_OVER			52	//pause
#define G_CD_FAULT_DATASAVE_PROCESS_ERROR	53	//warnning
#define G_CD_FAULT_ADC						54	//pause
#define G_CD_FAULT_OT						55	//shutdown

#define G_CD_FAULT_JIG_ACTIVE_ERROR			56	//pause
#define G_CD_FAULT_JIG_TRAY_ERROR			57	//pause
#define G_CD_FAULT_JIG_SMOKE_ERROR			58	//shutdown
#define G_CD_FAULT_JIG_TEMP_ERROR			59	//shutdown
#define G_CD_FAULT_JIG_GAS_ERROR			60	//shutdown
#define G_CD_FAULT_JIG_DOOR_ERROR			61	//pause
#define G_CD_FAULT_JIG_AIR_PRESS_ERROR		62	//pause
#define G_CD_FAULT_JIG_STACKER_ERROR		63	//pause

#define G_CD_FAULT_J_MAIN_CYL_UP_TIMEOUT	64	//pause
#define G_CD_FAULT_J_MAIN_CYL_DOWN_TIMEOUT	65
#define G_CD_FAULT_J_MAIN_CYL_UP_SENS		66
#define G_CD_FAULT_J_MAIN_CYL_DOWN_SENS		67
#define G_CD_FAULT_J_LATCH_CYL_OPEN_TIMEOUT	68
#define G_CD_FAULT_J_LATCH_CYL_CLOSE_TIMEOUT	69
#define G_CD_FAULT_J_LATCH_CYL_OPEN_SENS	70
#define G_CD_FAULT_J_LATCH_CYL_CLOSE_SENS	71
#define G_CD_FAULT_J_GRIP_CYL_OPEN_TIMEOUT	72
#define G_CD_FAULT_J_GRIP_CYL_CLOSE_TIMEOUT	73
#define G_CD_FAULT_J_GRIP_CYL_OPEN_SENS		74
#define G_CD_FAULT_J_GRIP_CYL_CLOSE_SENS	75
#define G_CD_FAULT_J_TRAY_STATUS_SENS		76
#define G_CD_FAULT_J_TRAY_DIR_SENS			77
#define G_CD_FAULT_J_DOOR_SENS				78
#define G_CD_FAULT_J_STK_SIGNAL_INVALID		79
#define G_CD_FAULT_J_STK_UNLOADING_END		80
#define G_CD_FAULT_J_TRAY_UNLOAD			81	//pause
#define M_CD_FAULT_EXT_OT					90	//shutdown  jhkw_160219

#define B_CD_NONE							0
#define B_CD_FAULT_OT						100	//shutdown
#define B_CD_FAULT_ADC						101	//pause

#define C_CD_NONE							0
#define C_CD_COM_START						200 //common code kjg_170810 120->200
#define C_CD_COM_FAULT_HW_UPPER_V			200	//alarm
#define C_CD_COM_FAULT_HW_LOWER_V			201	//alarm
#define C_CD_COM_FAULT_HW_UPPER_I			202	//alarm
#define C_CD_COM_FAULT_HW_LOWER_I			203	//alarm
#define C_CD_COM_FAULT_HW_UPPER_TEMP		204	//alarm
#define C_CD_COM_FAULT_HW_LOWER_TEMP		205	//alarm
#define C_CD_COM_FAULT_UPPER_V				206
#define C_CD_COM_FAULT_LOWER_V				207
#define C_CD_COM_FAULT_UPPER_I				208
#define C_CD_COM_FAULT_LOWER_I				209
#define C_CD_COM_FAULT_UPPER_AMPARE_HOUR	210
#define C_CD_COM_FAULT_LOWER_AMPARE_HOUR	211
#define C_CD_COM_FAULT_UPPER_TEMP			212	//alarm
#define C_CD_COM_FAULT_LOWER_TEMP			213 //alarm
#define C_CD_COM_FAULT_UPPER_CAPACITANCE	214
#define C_CD_COM_FAULT_LOWER_CAPACITANCE	215
#define C_CD_COM_FAULT_CHARGE_UPPER_V		216 //for formation start
#define C_CD_COM_FAULT_CHARGE_UPPER_AMPARE_HOUR	217
#define C_CD_COM_FAULT_CHARGE_END_UPPER_V	218
#define C_CD_COM_FAULT_CHARGE_LOWER_I		219
#define C_CD_COM_FAULT_DISCHARGE_LOWER_V	220
#define C_CD_COM_FAULT_DISCHARGE_RUN_TIME	221
#define C_CD_COM_FAULT_DISCHARGE_LOWER_AMPARE_HOUR	222
#define C_CD_COM_FAULT_OVER_CURRENT_LIMIT	223
#define C_CD_COM_FAULT_COMP_UPPER_V1		224
#define C_CD_COM_FAULT_COMP_LOWER_V1		225
#define C_CD_COM_FAULT_COMP_UPPER_V2		226
#define C_CD_COM_FAULT_COMP_LOWER_V2		227
#define C_CD_COM_FAULT_COMP_UPPER_V3		228
#define C_CD_COM_FAULT_COMP_LOWER_V3		229
#define C_CD_COM_FAULT_COMP_UPPER_I1		230
#define C_CD_COM_FAULT_COMP_LOWER_I1		231
#define C_CD_COM_FAULT_COMP_UPPER_I2		232
#define C_CD_COM_FAULT_COMP_LOWER_I2		233
#define C_CD_COM_FAULT_COMP_UPPER_I3		234
#define C_CD_COM_FAULT_COMP_LOWER_I3		235
#define C_CD_COM_FAULT_COMP_LOWER_CV_TIME	236
#define C_CD_COM_FAULT_COMP_UPPER_CV_TIME	237 //for formation end
#define C_CD_COM_FAULT_UPPER_P				238	
#define C_CD_COM_FAULT_LOWER_P				239
#define C_CD_COM_FAULT_UPPER_WATT_HOUR		240
#define C_CD_COM_FAULT_LOWER_WATT_HOUR		241
#define C_CD_COM_FAULT_COMP_AUX_V			242	//kjhw_150730
#define C_CD_COM_FAULT_TEMP_PAUSE			243	//jhkw_160123
#define C_CD_COM_FAULT_TEMP_CONTINUE		244	//jhkw_160123
#define C_CD_COM_FAULT_DELTA_V				245	//kjhw_160828
#define C_CD_COM_FAULT_FIX_UPPER_AUXV		246 //jhkw_200507s
#define C_CD_COM_FAULT_FIX_LOWER_AUXV		247
#define C_CD_COM_FAULT_FIX_UPPER_TEMP		248 //jhkw_200507e
#define C_CD_COM_FAULT_FIX_DELTA_I_AUXV		249 //shhw_230605 
#define C_CD_COM_END						299

#define C_CD_END_START						300 //end code //kjg_170810 220->300
#define C_CD_END_TIME						300
#define C_CD_END_V_UPPER					301
#define C_CD_END_I							302
#define C_CD_END_AMPARE_HOUR				303
#define C_CD_END_OCV						304
#define C_CD_END_STEP						305
#define C_CD_END_CHECK						306
#define C_CD_END_NEXT_STEP_CMD				307
#define C_CD_END_CYCLE						308
#define C_CD_END_LOOP						309
#define C_CD_END_Z							310
#define C_CD_END_DELTA_V					311
#define C_CD_END_DELTA_I					312
#define C_CD_END_VALUE_RATE_AMPARE_HOUR		313
#define C_CD_END_P							314
#define C_CD_END_WATT_HOUR					315
#define C_CD_END_V_LOWER					316
#define C_CD_END_CV_TIME					317
#define C_CD_END_GOTO_STEP_CMD				318
#define C_CD_END_STOP_CMD					319
#define C_CD_END_VALUE_RATE_WATT_HOUR		320
#define C_CD_END_SUM_AMPARE_HOUR			321
#define C_CD_END_SUM_WATT_HOUR				322
#define C_CD_END_SUM_TIME					323
#define C_CD_END_TEMP_UPPER					324
#define C_CD_END_TEMP_LOWER					325
#define C_CD_CHAMBER_CONTROL_WAIT			326
#define C_CD_CYCLE_CONTROL_WAIT				327
#define C_CD_END_INTERNAL_SKIP				328
#define C_CD_END_TIMESCH_TIME				329 //kjh_160418
#define C_CD_END_TEST_COND_UPDATE			330 //kjg_170810
#define C_CD_END_SOC						331 //20181219 KHK
#define C_CD_END_SEQUENCE_CHARGE			332	//jhkw_221205
#define C_CD_END_END						339

#define C_CD_SAVE_START						340 //save code //kjg_170810 260->340
#define C_CD_SAVE_DELTA_T					340
#define C_CD_SAVE_DELTA_V					341
#define C_CD_SAVE_DELTA_I					342
#define C_CD_SAVE_DELTA_TEMP				343
#define C_CD_SAVE_DELTA_P					344
#define C_CD_SAVE_TEST_COND_UPDATE			345 //kjg_170810
#define C_CD_SAVE_END						349

#define C_CD_FAULT_HARD_START				350	//hard fault code //kjg_170810 270->350
#define C_CD_FAULT_HW_UPPER_V				350 //alarm
#define C_CD_FAULT_HW_LOWER_V				351 //alarm
#define C_CD_FAULT_HW_UPPER_I				352 //alarm
#define C_CD_FAULT_HW_LOWER_I				353 //alarm
#define C_CD_FAULT_HW_OT					354 //alarm
#define C_CD_FAULT_CHANNEL_PS				355 //alarm
#define C_CD_FAULT_PS_OV					356 //alarm
#define C_CD_FAULT_PS_OC					357 //alarm
#define C_CD_FAULT_PS_DCOV					358 //alarm
#define C_CD_FAULT_IN_FUSE					359 //alarm
#define C_CD_FAULT_OUT_FUSE					360 //alarm
#define C_CD_FAULT_DELTA_V_FAIL				361
#define C_CD_FAULT_OUT_REACTOR_OT			362 //alarm
#define C_CD_FAULT_POWER_TRANS_OT			363 //alarm
#define C_CD_FAULT_POWER_REACTOR_OT			364 //alarm
#define C_CD_FAULT_RANGE					365 //alarm	//jhkw_130416
#define C_CD_FAULT_OC						366 //alarm	jhkw_131011
#define C_CD_FAULT_ETC						367 //alarm	jhkw_131011
#define C_CD_FAULT_OUT_PRECHARGING			368 //alarm	kjhw_150120
#define C_CD_FAULT_HARD_END					369

#define C_CD_FAULT_EXTERNAL_START			370 //external fault code //kjg_170810 290->370
#define C_CD_FAULT_M_CPU_WATCHDOG			370 //alarm
#define C_CD_FAULT_M_AC_POWER				371 //alarm
#define C_CD_FAULT_M_UPS_BATTERY			372 //alarm
#define C_CD_FAULT_M_EMG_SWITCH				373 //alarm
#define C_CD_FAULT_M_FORCE_POWER_SWITCH		374
#define C_CD_FAULT_M_FORCE_TERMINAL_HALT	375
#define C_CD_FAULT_M_FORCE_TERMINAL_QUIT	376
#define C_CD_FAULT_G_NETWORK_COMM			377
#define C_CD_FAULT_B_UPPER_TEMP				378 //alarm
#define C_CD_FAULT_B_ADC					379
#define C_CD_FAULT_CONTROL_PS				380 //alarm
#define C_CD_FAULT_READ_PATTERN_FILE		381
#define C_CD_FAULT_MAIN_PS					382 //alarm
#define C_CD_FAULT_CHAMBER_FAULT			383 //alarm
#define C_CD_FAULT_READ_USERMAP_FILE		384 //kjg_170810
#define C_CD_FAULT_READ_SOC_TRACKING_FILE	385 //20181219 KHK
#define C_CD_FAULT_CHAMBER_EMG				386 //alarm	//jhkw_191216s
#define C_CD_FAULT_CHAMBER_DOOR_OPEN		387 //alarm
#define C_CD_FAULT_CHAMBER_ETC				388 //alarm	//jhkw_191216e
#define C_CD_FAULT_READ_SQ_CHARGE_FILE		389 //jhkw_221205
#define C_CD_FAULT_EXTERNAL_END				399

#define C_CD_FAULT_CHECK_START				400 //check fault code //kjg_170810 320->400
#define	C_CD_FAULT_CHECK_NG					400
#define C_CD_FAULT_CHECK_UPPER_OCV			401
#define C_CD_FAULT_CHECK_LOWER_OCV			402
#define C_CD_FAULT_CHECK_UPPER_V			403
#define C_CD_FAULT_CHECK_LOWER_V			404
#define C_CD_FAULT_CHECK_UPPER_I			405
#define C_CD_FAULT_CHECK_LOWER_I			406
#define C_CD_FAULT_CHECK_ERROR_NO			407
#define C_CD_FAULT_CHECK_ERROR_YES			408
#define C_CD_FAULT_CHECK_DETECT_V			409	//for formation start
#define C_CD_FAULT_CHECK_REVERSE_V			410
#define C_CD_FAULT_CHECK_I_JUDGE_RATIO		411
#define C_CD_FAULT_CHECK_UPPER_DELTA_V		412
#define C_CD_FAULT_CHECK_LOWER_DELTA_V		413 //for formation end
#define C_CD_FAULT_CHECK_CONTACT_BAD1		414
#define C_CD_FAULT_CHECK_CONTACT_BAD2		415
#define C_CD_FAULT_CHECK_CONTACT_BAD3		416
#define C_CD_FAULT_CHECK_CONTACT_BAD4		417 //kjg_t_s
#define C_CD_FAULT_CHECK_CONTACT_BAD5		418
#define C_CD_FAULT_CHECK_CONTACT_BAD6		419
#define C_CD_FAULT_CHECK_CONTACT_BAD7		420
#define C_CD_FAULT_CHECK_CONTACT_BAD8		421
#define C_CD_FAULT_CHECK_CONTACT_BAD9		422 //kjg_t_e
#define C_CD_FAULT_CHECK_END				429

#define C_CD_FAULT_SOFT_START				430 //soft fault code //kjg_170810 350->430
#define	C_CD_FAULT_UPPER_V					430
#define	C_CD_FAULT_LOWER_V					431
#define C_CD_FAULT_UPPER_DELTA_V			432
#define C_CD_FAULT_LOWER_DELTA_V			433
#define C_CD_FAULT_UPPER_COMP_V1			434
#define C_CD_FAULT_LOWER_COMP_V1			435
#define C_CD_FAULT_UPPER_COMP_V2			436
#define C_CD_FAULT_LOWER_COMP_V2			437
#define C_CD_FAULT_UPPER_COMP_V3			438
#define C_CD_FAULT_LOWER_COMP_V3			439
#define C_CD_FAULT_UPPER_OCV				440
#define C_CD_FAULT_LOWER_OCV				441
#define	C_CD_FAULT_UPPER_I					442
#define C_CD_FAULT_LOWER_I					443
#define C_CD_FAULT_UPPER_DELTA_I			444
#define C_CD_FAULT_LOWER_DELTA_I			445
#define C_CD_FAULT_UPPER_COMP_I1			446
#define C_CD_FAULT_LOWER_COMP_I1			447
#define C_CD_FAULT_UPPER_T					448
#define C_CD_FAULT_LOWER_T					449
#define C_CD_FAULT_UPPER_AMPARE_HOUR		450
#define	C_CD_FAULT_LOWER_AMPARE_HOUR		451
#define C_CD_FAULT_UPPER_DELTA_C			452
#define	C_CD_FAULT_LOWER_DELTA_C			453
#define C_CD_FAULT_UPPER_COMP_C				454
#define	C_CD_FAULT_LOWER_COMP_C				455
#define C_CD_FAULT_UPPER_Z					456
#define C_CD_FAULT_LOWER_Z					457
#define C_CD_FAULT_UPPER_TEMP				458
#define C_CD_FAULT_LOWER_TEMP				459
#define C_CD_FAULT_DELTA_TEMP				460
#define C_CD_FAULT_UPPER_COMP_I2			461
#define C_CD_FAULT_LOWER_COMP_I2			462
#define C_CD_FAULT_UPPER_COMP_I3			463
#define C_CD_FAULT_LOWER_COMP_I3			464
#define C_CD_FAULT_STOP_START				465 //fault_stop start //kjg_170810 385->465
#define C_CD_FAULT_STOP_V					465
#define C_CD_FAULT_STOP_I					466
#define C_CD_FAULT_STOP_T					467
#define C_CD_FAULT_STOP_C					468
#define C_CD_FAULT_STOP_P					469
#define C_CD_FAULT_STOP_WATT_HOUR			470
#define C_CD_FAULT_STOP_CMD					471
#define C_CD_FAULT_STOP_END					471 //fault_stop end //kjg_170810 391->471
#define C_CD_FAULT_PAUSE_CMD				472
#define C_CD_FAULT_ACC_CYCLE_COUNT			473
#define C_CD_FAULT_UPPER_CAPACITANCE		474
#define C_CD_FAULT_LOWER_CAPACITANCE		475
#define C_CD_FAULT_UPPER_WATT_HOUR			476
#define	C_CD_FAULT_LOWER_WATT_HOUR			477
#define C_CD_FAULT_MULTI_CYCLE_COUNT		478
#define C_CD_FAULT_RUN_HOLD					479
#define C_CD_FAULT_VOLTAGE_DATA_MIN			480 //for formation ng condition start
#define C_CD_FAULT_VOLTAGE_DATA_MAX			481
#define C_CD_FAULT_VOLTAGE_AVG_MIN			482
#define C_CD_FAULT_VOLTAGE_AVG_MAX			483
#define C_CD_FAULT_AMPARE_HOUR_DATA_MIN		484
#define C_CD_FAULT_AMPARE_HOUR_DATA_MAX		485
#define C_CD_FAULT_AMPARE_HOUR_AVG_MIN		486
#define C_CD_FAULT_AMPARE_HOUR_AVG_MAX		487
#define C_CD_FAULT_POWER_DATA_MIN			488
#define C_CD_FAULT_POWER_DATA_MAX			489
#define C_CD_FAULT_POWER_AVG_MIN			490
#define C_CD_FAULT_POWER_AVG_MAX			491 //for formation ng condition end
#define C_CD_FAULT_BAD_CELL					492
#define C_CD_FAULT_STOP_V_LIMITED			493 //jhkw_131023
//#define C_CD_FAULT_STOP_USERMAP_FUNC_ERR	494 //kjhw_140828
#define C_CD_FAULT_STOP_MUX_SELECT_ERR		495 //kjhw_151021
/*#define C_CD_FAULT_COND_LOW_DELTA_V			496	//jhkw_180823s
#define C_CD_FAULT_COND_LOW_DELTA_I			497
#define C_CD_FAULT_COND_UP_DELTA_V			498
#define C_CD_FAULT_COND_UP_DELTA_I			499	*///jhkw_180823e
#define C_CD_FAULT_CELL_BALANCING_ERROR		500	//jhkw_190120
#define C_CD_FAULT_CHAMBER_ERROR_GUI		501	//jhkw_201102
#define C_CD_FAULT_CHILLER_ERROR_GUI		502	//jhkw_201102
#define C_CD_FAULT_SOFT_END					579

#define C_CD_AUX_START						580 //aux code //kjg_170810 500->580
#define C_CD_AUX_END_START					580
#define C_CD_AUX_END_UPPER_TEMP				580
#define C_CD_AUX_END_LOWER_TEMP				581
#define C_CD_AUX_END_UPPER_V				582
#define C_CD_AUX_END_LOWER_V				583
#define C_CD_AUX_END_UPPER_V_BRANCH			584
#define C_CD_AUX_END_LOWER_V_BRANCH			585
#define C_CD_AUX_END_UPPER_TEMP_BRANCH		586
#define C_CD_AUX_END_LOWER_TEMP_BRANCH		587
#define C_CD_AUX_END_FUNC_DIV_1				588
#define C_CD_AUX_END_FUNC_DIV_2				589
#define C_CD_AUX_END_FUNC_DIV_3				590
#define C_CD_AUX_END_FUNC_DIV_4				591
#define C_CD_AUX_END_FUNC_DIV_5				592
#define C_CD_AUX_END_FUNC_DIV_6				593
#define C_CD_AUX_END_FUNC_DIV_7				594
#define C_CD_AUX_END_FUNC_DIV_8				595
#define C_CD_AUX_END_FUNC_DIV_9				596
#define C_CD_AUX_END_FUNC_DIV_10			597
#define C_CD_AUX_END_END					609
#define C_CD_AUX_FAULT_START				610
#define C_CD_COM_AUX_FAULT_FUNC_DIV_1		610
#define C_CD_COM_AUX_FAULT_FUNC_DIV_2		611
#define C_CD_COM_AUX_FAULT_FUNC_DIV_3		612
#define C_CD_COM_AUX_FAULT_FUNC_DIV_4		613
#define C_CD_COM_AUX_FAULT_FUNC_DIV_5		614
#define C_CD_COM_AUX_FAULT_FUNC_DIV_6		615
#define C_CD_COM_AUX_FAULT_FUNC_DIV_7		616
#define C_CD_COM_AUX_FAULT_FUNC_DIV_8		617
#define C_CD_COM_AUX_FAULT_FUNC_DIV_9		618
#define C_CD_COM_AUX_FAULT_FUNC_DIV_10		619
#define C_CD_AUX_FAULT_UPPER_TEMP			620
#define C_CD_AUX_FAULT_LOWER_TEMP			621
#define C_CD_AUX_FAULT_UPPER_V				622
#define C_CD_AUX_FAULT_LOWER_V				623
#define C_CD_AUX_FAULT_FUNC_DIV_1			624
#define C_CD_AUX_FAULT_FUNC_DIV_2			625
#define C_CD_AUX_FAULT_FUNC_DIV_3			626
#define C_CD_AUX_FAULT_FUNC_DIV_4			627
#define C_CD_AUX_FAULT_FUNC_DIV_5			628
#define C_CD_AUX_FAULT_FUNC_DIV_6			629
#define C_CD_AUX_FAULT_FUNC_DIV_7			630
#define C_CD_AUX_FAULT_FUNC_DIV_8			631
#define C_CD_AUX_FAULT_FUNC_DIV_9			632
#define C_CD_AUX_FAULT_FUNC_DIV_10			633
#define C_CD_AUX_FAULT_END					679
#define C_CD_AUX_END						679

#define C_CD_CAN_START						680 //can code //kjg_170810 600->680
#define C_CD_CAN_END_START					680
#define C_CD_CAN_END_UPPER					680
#define C_CD_CAN_END_LOWER					681
#define C_CD_CAN_END_UPPER_V_BRANCH			682
#define C_CD_CAN_END_LOWER_V_BRANCH			683
#define C_CD_CAN_END_UPPER_TEMP_BRANCH		684
#define C_CD_CAN_END_LOWER_TEMP_BRANCH		685
#define C_CD_CAN_END_UPPER_SOC_BRANCH		686
#define C_CD_CAN_END_LOWER_SOC_BRANCH		687
#define C_CD_CAN_END_FAULT_BRANCH			688
#define C_CD_CAN_END_FUNC_DIV_1				689
#define C_CD_CAN_END_FUNC_DIV_2				690
#define C_CD_CAN_END_FUNC_DIV_3				691
#define C_CD_CAN_END_FUNC_DIV_4				692
#define C_CD_CAN_END_FUNC_DIV_5				693
#define C_CD_CAN_END_FUNC_DIV_6				694
#define C_CD_CAN_END_FUNC_DIV_7				695
#define C_CD_CAN_END_FUNC_DIV_8				696
#define C_CD_CAN_END_FUNC_DIV_9				697
#define C_CD_CAN_END_FUNC_DIV_10			698
#define C_CD_CAN_END_BMS_ERROR				699
#define C_CD_CAN_END_END					709
#define C_CD_CAN_FAULT_START				710
#define C_CD_COM_CAN_FAULT_FUNC_DIV_1		710
#define C_CD_COM_CAN_FAULT_FUNC_DIV_2		711
#define C_CD_COM_CAN_FAULT_FUNC_DIV_3		712
#define C_CD_COM_CAN_FAULT_FUNC_DIV_4		713
#define C_CD_COM_CAN_FAULT_FUNC_DIV_5		714
#define C_CD_COM_CAN_FAULT_FUNC_DIV_6		715
#define C_CD_COM_CAN_FAULT_FUNC_DIV_7		716
#define C_CD_COM_CAN_FAULT_FUNC_DIV_8		717
#define C_CD_COM_CAN_FAULT_FUNC_DIV_9		718
#define C_CD_COM_CAN_FAULT_FUNC_DIV_10		719
#define C_CD_CAN_FAULT_UPPER				720
#define C_CD_CAN_FAULT_LOWER				721
#define C_CD_CAN_FAULT_FUNC_DIV_1			722
#define C_CD_CAN_FAULT_FUNC_DIV_2			723
#define C_CD_CAN_FAULT_FUNC_DIV_3			724
#define C_CD_CAN_FAULT_FUNC_DIV_4			725
#define C_CD_CAN_FAULT_FUNC_DIV_5			726
#define C_CD_CAN_FAULT_FUNC_DIV_6			727
#define C_CD_CAN_FAULT_FUNC_DIV_7			728
#define C_CD_CAN_FAULT_FUNC_DIV_8			729
#define C_CD_CAN_FAULT_FUNC_DIV_9			730
#define C_CD_CAN_FAULT_FUNC_DIV_10			731
#define C_CD_CAN_FAULT_BMS_PAUSE			732
#define C_CD_CAN_CABLE_FAULT				733
#define C_CD_CAN_FAULT_EXT_DEVICE			734 //kjg_140916_s
#define C_CD_CAN_FAULT_EXT_CMD_RANGE		735
#define C_CD_CAN_FAULT_EXT_CONTROLLER_STATE	736
#define C_CD_CAN_FAULT_EXT_NM_PERIOD		737 //kjg_140916_e
#define C_CD_CAN_FAULT_END					779
#define C_CD_CAN_END						779

//Time Value
#define TIME_1SEC							1000
#define TIME_2SEC							2000

//internal io addr
#define I_ADDR_IN_1							HW_I_ADDR_IN_1
#define I_ADDR_IN_2							HW_I_ADDR_IN_2
#define I_ADDR_OUT_1						HW_I_ADDR_OUT_1
#define I_ADDR_OUT_2						HW_I_ADDR_OUT_2

//module io addr
#define M_ADDR_IN_1							HW_M_ADDR_IN_1
#define M_ADDR_IN_2							HW_M_ADDR_IN_2
#define M_ADDR_IN_3							HW_M_ADDR_IN_3
#define M_ADDR_IN_4							HW_M_ADDR_IN_4
#define M_ADDR_OUT_1						HW_M_ADDR_OUT_1
#define M_ADDR_OUT_2						HW_M_ADDR_OUT_2

//dio addr
#define D_ADDR_IN_1							HW_D_ADDR_IN_1
#define D_ADDR_OUT_1						HW_D_ADDR_OUT_1

//ch addr
#define CH_ADDR_MUX_1						HW_CH_ADDR_MUX_1
#define CH_ADDR_MUX_2						HW_CH_ADDR_MUX_2
#define CH_ADDR_MUX_3						HW_CH_ADDR_MUX_3
#define CH_ADDR_MUX_4						HW_CH_ADDR_MUX_4
#define CH_ADDR_DAV_SYNC					HW_CH_ADDR_DAV_SYNC
#define CH_ADDR_DAV_DATA_H					HW_CH_ADDR_DAV_DATA_H
#define CH_ADDR_DAV_DATA_L					HW_CH_ADDR_DAV_DATA_L
#define CH_ADDR_DAI_SYNC					HW_CH_ADDR_DAI_SYNC
#define CH_ADDR_DAI_DATA_H					HW_CH_ADDR_DAI_DATA_H
#define CH_ADDR_DAI_DATA_L					HW_CH_ADDR_DAI_DATA_L
#define CH_ADDR_AD_START					HW_CH_ADDR_AD_START
#define CH_ADDR_AD_DATA_H_A1				HW_CH_ADDR_AD_DATA_H_A1
#define CH_ADDR_AD_DATA_L_A1				HW_CH_ADDR_AD_DATA_L_A1
#define CH_ADDR_AD_DATA_H_A2				HW_CH_ADDR_AD_DATA_H_A2
#define CH_ADDR_AD_DATA_L_A2				HW_CH_ADDR_AD_DATA_L_A2
#define CH_ADDR_AD_DATA_H_A3				HW_CH_ADDR_AD_DATA_H_A3
#define CH_ADDR_AD_DATA_L_A3				HW_CH_ADDR_AD_DATA_L_A3
#define CH_ADDR_AD_DATA_H_B1				HW_CH_ADDR_AD_DATA_H_B1
#define CH_ADDR_AD_DATA_L_B1				HW_CH_ADDR_AD_DATA_L_B1
#define CH_ADDR_AD_DATA_H_B2				HW_CH_ADDR_AD_DATA_H_B2
#define CH_ADDR_AD_DATA_L_B2				HW_CH_ADDR_AD_DATA_L_B2
#define CH_ADDR_AD_DATA_H_B3				HW_CH_ADDR_AD_DATA_H_B3
#define CH_ADDR_AD_DATA_L_B3				HW_CH_ADDR_AD_DATA_L_B3

//common cmd define
#define MAX_CMD_MODE						4

//cmd mode
#define CMD_MODE_USER						0
#define CMD_MODE_STEP						1

//cmd type
#define CMD_TYPE_NONE						0
#define CMD_TYPE_RUN						1
#define CMD_TYPE_STOP						2
#define CMD_TYPE_PAUSE						3
#define CMD_TYPE_NET_PAUSE					4
#define CMD_TYPE_CONTINUE					5
#define CMD_TYPE_NEXT_STEP					6
#define CMD_TYPE_RESET						7
#define CMD_TYPE_CLEAR						8
#define CMD_TYPE_CHECK						9
#define CMD_TYPE_CALI						10
#define CMD_TYPE_CHECK_PAUSE				11

#define BCR_SIZE							64

#endif
