#ifndef __SUBSENSV_DEF_H__
#define __SUBSENSV_DEF_H__

//SubSensV define
#define MAX_SUB_SENS_V_DATA			256
//#define MAX_SUB_SENS_V_DATA			512	//kjg_180914
#define MAX_SUB_SENS_V_REF_INDEX	3
#define MAX_SUB_SENS_V_CH_INDEX		8
#define MAX_SUB_SENS_V_CH_HALF_INDEX	4 //lki_111010 NO_DMA_DAQ
#define MAX_SUB_SENS_V_AD_SLOT		4
#define MAX_SUB_SENS_V_ADC_INDEX_1	2	//DAQ_TYPE1
#define MAX_SUB_SENS_V_ADC_INDEX_2	4	//DAQ_TYPE2
#define MAX_SUB_SENS_V_ADC_INDEX	4
//#define MAX_SUB_SENS_V_FILTER_AD_COUNT	4
#define MAX_SUB_SENS_V_FILTER_AD_COUNT	8
#define MAX_SUB_SENS_V_SOURCE_SENS_COUNT	12
//kjhw_140527
#define MAX_SUB_SENS_V_BUFF			(SUB_SENS_V_ZERO_VAL + (MAX_SUB_SENS_V_REF_INDEX * MAX_SUB_SENS_V_AD_SLOT * MAX_SUB_SENS_V_ADC_INDEX * 2) + (MAX_SUB_SENS_V_CH_INDEX * MAX_SUB_SENS_V_AD_SLOT * MAX_SUB_SENS_V_ADC_INDEX * 2) + 2)

//etc
#define SUB_SENS_V_ZERO_VAL			6

//SubSensV Signal
#define SUB_SENS_SIG_DAQ_DIVISION	0
#define SUB_SENS_SIG_DAQ_ISOLATION	1
#define TH_TABLE_PHASE				2
#define TH_TABLE_READ_FLAG			3
//#define SUB_SENS_SIG_DAQ_CH_DATA_PHASE	2 //kjg_180914
//#define SUB_SENS_SIG_DAQ_CH_DATA_SEL	3 //kjg_180914

#endif
