#!/bin/bash

# AppControl_Config modification script
config_file_app="/root/system_data/config/parameter/AppControl_Config"

cp "$config_file_app" "$config_file_app.bak"

new_modelName="PSCSA-P1026-S02-R004-N001"
new_versionNo="250725"
new_update_date="250725"

export new_modelName new_versionNo new_update_date

awk -v new_modelName="$new_modelName" 'BEGIN {
    FS = ":"
    OFS = ":"
}
$1 ~ /modelName/ {
    # Replace model name with new_modelName, ensuring that the correct part is replaced
    sub(/PSCSB-[^-]+-[^-]+-[^-]+-[^-]+/, new_modelName, $2); 
    print;
    next
}
$1 ~ /versionNo/ {
    print "versionNo           :   " ENVIRON["new_versionNo"];
    next
}
$1 ~ /update_date/ {
    print "update_date         :   " ENVIRON["new_update_date"];
    next
}
{
    # Print other lines as is without altering them
    print
}' "$config_file_app.bak" > "$config_file_app.tmp"

mv "$config_file_app.tmp" "$config_file_app"

rm -rf "$config_file_app.bak"

echo "AppControl_Config fix."

config_file_m="/root/system_data/config/parameter/mControl_Config"

cp "$config_file_m" "$config_file_m.bak"

awk 'BEGIN {
    FS = ":"
    OFS = ":"
}
$1 ~ /multi_temp_cali/ {
    # Print the existing line as is
    print;
    # Add the new 'BreakDownCheck' line with a proper tab after ':'
    printf "BreakDownCheck      :   1\n";
    next
}
{
    # Print other lines as is, without changing them
    print
}' "$config_file_m.bak" > "$config_file_m.tmp"

mv "$config_file_m.tmp" "$config_file_m"

rm -rf "$config_file_m.bak"

echo "BreakDownCheck added to mControl_Config."



# CAN_TYPE FIX
config_file_can="/root/system_data/config/parameter/can_comm/CanConfig"

cp "$config_file_can" "$config_file_can.bak"

new_CanType="1"

export new_CanType

awk -v new_CanType="$new_CanType" 'BEGIN {

    FS = ":"
    OFS = ":"
}
$1 ~ /commType/ {
    print "commType		:	" ENVIRON["new_CanType"];
    next
}
{
	print
}' "$config_file_can.bak" > "$config_file_can.tmp"

mv "$config_file_can.tmp" "$config_file_can"

rm -rf "$config_file_can.bak"

echo "CanConfig fix."


# Client_Config Protocal_Version UP
config_file_client="/root/system_data/config/parameter/client/COA1/Client_Config"

cp "$config_file_client" "$config_file_client.bak"

new_ProtocalNo="4134"

export new_ProtocalNo

awk -v new_ProtocalNo="$new_ProtocalNo" 'BEGIN {
    FS = ":"
    OFS = ":"
}
$1 ~ /protocol_version/ {
    print "protocol_version	:	" ENVIRON["new_ProtocalNo"];
    next
}
{
	print
}' "$config_file_client.bak" > "$config_file_client.tmp"

mv "$config_file_client.tmp" "$config_file_client"

rm -rf "$config_file_client.bak"

echo "protocal version fix to Clinet_Config."


cd /project/system_mcts

rm -rf current

cd /root/update/backup_program

mv current_backup /project/system_mcts/current

cd /project/system_mcts/current/

cd App/AppControl

make all_coa

./clear

cd /root/system_data/config/parameter

echo "$new_modelName" > sbc_info

echo "current_update done"

rm -rf /root/update/ok.txt

rm -rf /root/update/Auto_Update.tar.gz

rm -rf /root/update/backup_program

rm -rf /root/update/SBC_Update

#Reboot system
reboot

