#Automatically generated by RTLinux Makefile
RTL_DIR = /usr/src/rtlinux-3.2-pre2
RTLINUX_DIR = /usr/src/linux
INCLUDE= -I/usr/src/linux/include -I/usr/src/rtlinux-3.2-pre2/include -I/usr/src/rtlinux-3.2-pre2/include/compat 
CFLAGS = -mhard-float -D__KERNEL__ -Wall -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -pipe -mpreferred-stack-boundary=2 -march=i586 -DMODULE -DMODVERSIONS -include /usr/src/linux-2.4.19/include/linux/modversions.h -g -D__RTL__ -D_LOOSE_KERNEL_NAMES -O2 -I/usr/src/linux/include -I/usr/src/rtlinux-3.2-pre2/include -I/usr/src/rtlinux-3.2-pre2/include/compat -I/usr/src/rtlinux-3.2-pre2/include/posix
ARCH = i386
CC = gcc
CXXFLAGS = -D__KERNEL__ -Wall -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -pipe -mpreferred-stack-boundary=2 -march=i586 -DMODULE -DMODVERSIONS -include /usr/src/linux-2.4.19/include/linux/modversions.h -g -D__RTL__ -D_LOOSE_KERNEL_NAMES -I/usr/src/linux/include -I/usr/src/rtlinux-3.2-pre2/include -I/usr/src/rtlinux-3.2-pre2/include/compat -I/usr/src/rtlinux-3.2-pre2/include/posix -fno-exceptions -fno-rtti
